<?php
declare(strict_types=1);

/** @version 0.4.3 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Template $block */
/** @var TemplateRenderer $templateRenderer */
/** @var Escaper $escaper */
/** @var $option string[]|array[] */

$option = $block->getOption();
?>
<?php if (is_array($option['value'])): ?>
    <optgroup label="<?= $escaper->escapeHtml(str_repeat('&nbsp;', $option['level'])) ?><?= $escaper->escapeHtml($option['label']) ?>"></optgroup>
    <?php foreach ($option['value'] as $suboption): ?>
        <?php $suboption['level'] = $option['level'] + 1; ?>
        <?= /* @noEscape */ $templateRenderer->html(
            $block,
            'Loki_AdminComponents::form/field_type/select/option.phtml',
            ['option' => $suboption]
        ) ?>
    <?php endforeach; ?>
<?php else: ?>
    <option value="<?= $escaper->escapeHtml($option['value']) ?>">
        <?= $escaper->escapeHtml(str_repeat('&nbsp;', $option['level'])) ?>
        <?= $escaper->escapeHtml($option['label']) ?>
    </option>
<?php endif; ?>
