<?php declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 0.7.2 */
/** @var Escaper $escaper */
/** @var Template $block */
?>
<style>
    .admin__action-multiselect-crumb + .admin__action-multiselect-crumb {
        margin-left: 1rem;
    }
</style>
<template x-for="categoryId in selectedCategoryIds" :key="categoryId">
    <span class="<?= $escaper->escapeHtml($css('admin__action-multiselect-crumb', '@todo')) ?>"
          x-data="CategorySelectionCrumb"
          :data-id="categoryId"
    >
        <span x-text="crumbLabel"></span>
        <button
            class="<?= $escaper->escapeHtml($css('action-close', '@todo')) ?>"
            type="button"
            data-action="remove-selected-item"
            tabindex="-1"
            @click="removeSelected"
        >
            <span class="<?= $escaper->escapeHtml($css('action-close-text', '@todo')) ?>">
                <?= $escaper->escapeHtml(__('Close')) ?>
            </span>
        </button>
    </span>
</template>
<script>
    'use strict';

    function CategorySelectionCrumb() {
        return {
            root: null,
            crumbId: null,
            init() {
                this.root = this.$el;
                this.$nextTick(() => {
                    this.crumbId = parseFloat(this.root.dataset.id);
                });
            },
            crumbLabel() {
                return this.itemLabel(this.crumbId);
            },
            removeSelected() {
                this.$event.stopPropagation();
                this.unselectCategoryId(this.crumbId);
            },
        };
    }

    document.addEventListener('alpine:init', () => {
        Alpine.data('CategorySelectionCrumb', CategorySelectionCrumb);
    });
</script>
