<?php declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 0.7.2 */
/** @var Escaper $escaper */
/** @var Template $block */
?>
<div
    class="<?= $escaper->escapeHtml($css('admin__action-multiselect-search-wrap', '@todo')) ?>"
    x-data="CategoriesSelectionSearch"
>
    <input
        id="category-search-input"
        class="<?= $escaper->escapeHtml($css('admin__control-text admin__action-multiselect-search', '@todo')) ?>"
        data-role="advanced-select-text"
        type="text"
        @input="filterInputValue"
    />
    <label class="<?= $escaper->escapeHtml($css('admin__action-multiselect-search-label', '@todo')) ?>"
           data-action="advanced-select-search"
           for="category-search-input"
    ></label>
    <template x-if="canShowSearchResult">
        <div
            class="<?= $escaper->escapeHtml($css('admin__action-multiselect-search-count', '@todo')) ?>"
            x-text="itemsQuantity"
        ></div>
    </template>
</div>
<template x-if="canShowSearchResult">
<ul class="<?= $escaper->escapeHtml($css('admin__action-multiselect-menu-inner _root', '@todo')) ?>">
    <template x-for="search in searchResult" :key="search.id">
        <li class="<?= $escaper->escapeHtml($css('admin__action-multiselect-menu-inner-item _root', '@todo')) ?>"
            :data-search-item-id="search.id"
            x-data="CategoriesSelectionSearchResultItem"
            data-bind="css: { _parent: $data.optgroup }"
            data-role="option-group"
        >
            <div
                class="<?= $escaper->escapeHtml($css('action-menu-item', '@todo')) ?>"
                :class="<?= $escaper->escapeHtml($css('classActionMenuItem', '@todo')) ?>"
                @click="toggleSelection"
            >
                <input
                    class="<?= $escaper->escapeHtml($css('admin__control-checkbox', '@todo')) ?>"
                    type="checkbox"
                    tabindex="-1"
                    :checked="isSelected"
                />
                <label class="<?= $escaper->escapeHtml($css('admin__action-multiselect-label', '@todo')) ?>">
                    <span x-text="search.label"></span>
                    <template x-if="hasParent">
                        <span
                            class="<?= $escaper->escapeHtml($css('admin__action-multiselect-item-path', '@todo')) ?>"
                            x-text="parentsPathText"></span>
                    </template>
                </label>
            </div>
        </li>
    </template>
</ul>
</template>
<template x-if="canShowNoResultMessage">
    <div style="padding: 2rem; text-align: center;">
        <?= $escaper->escapeHtml(__('No results found.')) ?>
    </div>
</template>

<script>
    'use strict';

    function CategoriesSelectionSearch() {
        return {
            itemsQuantity() {
                return this.searchResult.length === 1 ?
                    "1 <?= $escaper->escapeJs(__('option')) ?>" :
                    this.searchResult.length.toString() + " <?= $escaper->escapeJs(__('options')) ?>";
            },
            filterInputValue() {
                const searchValue = this.$event.target.value.trim().toLowerCase();

                if (!searchValue) {
                    this.searchResult = [];
                    return this.switchToTreeView();
                }

                this.searchResult = this.prepareFilteredResult(searchValue);

                this.switchToSearchView();
            },
            switchToSearchView() {
                if (!this.isSearchView) {
                    this.isTreeView = false;
                    this.isSearchView = true;
                }
            },
            switchToTreeView() {
                if (!this.isTreeView) {
                    this.isTreeView = true;
                    this.isSearchView = false;
                }
            },
            prepareFilteredResult(value) {
                const result = [];

                Object.keys(this.items).forEach((itemId) => {
                    const item = this.items[itemId];
                    const currentOption = item.label.toLowerCase();

                    if (currentOption.indexOf(value) > -1) {
                        result.push(item);
                    }
                });

                return result;
            },
        };
    }

    function CategoriesSelectionSearchResultItem() {
        return {
            ...CategorySelectItemCommon(),
            get itemId() {
                return this.data?.id;
            },
            init() {
                this.$nextTick(() => {
                    const searchItemId = parseFloat(this.$el.dataset.searchItemId);
                    this.data = this.items[searchItemId];
                });
            },
            hasParent() {
                return !!this.data?.parentId;
            },
            parentsPathText() {
                if (!this.data) {
                    return '';
                }

                const parentsPath = this.items[this.itemId].parentsPath;
                if (parentsPath !== null) {
                    return parentsPath;
                }

                let paths = [];

                this.data.parentIds.forEach((parentId) => {
                    paths.push(this.items[parentId].label);
                });

                this.items[this.itemId].parentsPath = paths.join(' / ');

                return this.items[this.itemId].parentsPath;
            },
        };
    }

    document.addEventListener('alpine:init', () => {
        Alpine.data('CategoriesSelectionSearch', CategoriesSelectionSearch);
        Alpine.data('CategoriesSelectionSearchResultItem', CategoriesSelectionSearchResultItem);
    });
</script>
