<?php declare(strict_types=1);

use Loki\AdminComponents\Data\CategoryTreeNode;
use Loki\AdminComponents\Form\Field\FieldType\CategorySelection;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Form\Field\Field;

/** @version 0.7.2 */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var Field $field */
/** @var CategorySelection $fieldType */
/** @var CategoryTreeNode $categoryTreeNode */

$field = $block->getData('field');
$categoryTreeNode = $block->getData('category_tree_node');
$fieldType = $field->getFieldType();
?>
<ul class="<?= $escaper->escapeHtml($css('admin__action-multiselect-menu-inner', '@todo')) ?>"
    data-item-data="<?= $escaper->escapeHtmlAttr($fieldType->getCategoryNodeJson($categoryTreeNode)) ?>"
    x-data="CategorySelectItem"
    x-show="canShow"
    :data-level="itemLevel"
    :data-expanded="dataExpanded"
>
    <li class="<?= $escaper->escapeHtml($css('admin__action-multiselect-menu-inner-item', '@todo')) ?>"
        :class="<?= $escaper->escapeHtml($css('classInnerItem', '@todo')) ?>"
    >
        <div class="<?= $escaper->escapeHtml($css('action-menu-item', '@todo')) ?>"
             :class="<?= $escaper->escapeHtml($css('classActionMenuItem', '@todo')) ?>"
             @mouseenter="handleMouseEnter"
             @mouseleave="handleMouseLeave"
             @click="toggleSelection"
             @keydown.enter.window="toggleSelection"
        >
            <template x-if="showIconToOpenLevels">
                <div class="<?= $escaper->escapeHtml($css('admin__action-multiselect-dropdown', '@todo')) ?>"
                     @click="toggleExpansion"
                ></div>
            </template>
            <input
                class="<?= $escaper->escapeHtml($css('admin__control-checkbox', '@todo')) ?>"
                type="checkbox"
                tabindex="-1"
                :checked="isSelected"
            />
            <label class="<?= $escaper->escapeHtml($css('admin__action-multiselect-label', '@todo')) ?>">
                <?= $escaper->escapeHtmlAttr($categoryTreeNode->label) ?>
            </label>
        </div>
        <?php foreach ($categoryTreeNode->children as $childCategory): ?>
            <?= /** @noEscape */ $fieldType->renderChildCategoryNode($childCategory, $field)?>
        <?php endforeach; ?>
    </li>
</ul>
