<?php
declare(strict_types=1);

/** @version 0.6.4 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    const LokiAdminColumnsSelectorComponentPartial = {
        activeColumns: null,
        isColumnActive() {
            const columnName = this.$el.getAttribute('data-column');
            return this.activeColumns.includes(columnName);
        },
        showColumnsSelector: false,
        toggleColumnsSelector() {
            this.showColumnsSelector = !this.showColumnsSelector;
        },
        toggleActiveColumn() {
            const columnName = this.$el.getAttribute('data-column');
            if (this.activeColumns.includes(columnName)) {
                this.activeColumns = this.activeColumns.filter(item => item !== columnName);
            } else {
                this.activeColumns.push(columnName);
            }

            this.post({activeColumns: this.activeColumns});
        }
    }
</script>
