<?php
declare(strict_types=1);

/** @version 0.5.1 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    const LokiAdminFiltersComponentPartial = {
        filters: [],
        showFilters: false,
        toggleFilters() {
            this.showFilters = !this.showFilters;
        },
        filterButtonClass() {
            return this.showFilters ? '_active' : '';
        },
        applyFilters() {
            this.post({filters: this.filters});
        }
    }
</script>
