<?php
declare(strict_types=1);
?>
<script>
    const LokiAdminInlineEditComponentPartial = {
        showInlineEdit: false,
        hideInlineEdit() {
            return !this.showInlineEdit;
        },
        toggleInlineEdit() {
            this.showInlineEdit = !this.showInlineEdit;
        },
        saveInlineEdit(event) {
            const postData = {
                inline_edit: {
                    identifier: event.target.getAttribute('data-identifier'),
                    property: event.target.getAttribute('data-property'),
                    value: this.$refs.inlineEditField.value,
                }
            };

            this.post(postData);
        },
    }
</script>
