<?php
declare(strict_types=1);

/** @version 0.3.3 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    const LokiAdminPaginationComponentPartial = {
        changePage(event) {
            if (!event) {
                return;
            }

            this.post({page: event.target.value});
        },
        nextPage() {
            this.post({page: this.page + 1});
        },
        previousPage(event) {
            this.post({page: this.page - 1});
        }
    }
</script>
