<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiAdminComponents\Component\Form\FormViewModel;
use Yireo\LokiAdminComponents\Form\Fieldset\Field;
use Yireo\LokiComponents\Util\Block\ChildRenderer;

/** @var Template $block */
/** @var Field $field */
/** @var FormViewModel $viewModel */
/** @var ChildRenderer $childRenderer */

$viewModel = $block->getViewModel();
$buttons = $viewModel->getButtons();


$mainSaveAction = false;
$otherSaveActions = [];
?>
<div class="page-main-actions">
    <div class="page-actions-placeholder"></div>
    <div class="page-actions">
        <div class="page-actions-inner">
            <div class="page-actions-buttons">
                <?php foreach ($buttons as $button) : ?>
                    <?php $subButtons = $button->getSubButtons(); ?>
                    <button
                        @click="<?= $button->getMethod() ?>"
                        title="<?= __($button->getLabel()) ?>"
                        type="button"
                        class="action- scalable <?= $button->getCssClass() ?>">
                        <span><?= __($button->getLabel()) ?></span>
                    </button>
                <?php endforeach; ?>

                <?php if (!empty($otherSaveActions)) : ?>
                    <div title="Save and Continue" class="actions-split save primary">
                        <button @click="saveAndContinueAction" title="Save and Continue" class="action-default primary">
                            <span>Save and Continue</span>
                        </button>

                        <button @click="toggleOtherActions" title="Save and Continue"
                                class="action-toggle primary save">
                            <span>Select</span>
                        </button>

                        <ul class="dropdown-menu" x-cloak x-show="showOtherActions">
                            <?php foreach ($otherSaveActions as $otherSaveAction): ?>
                                <li>
                            <span @click="saveAndDuplicateAction" title="Save &amp; Duplicate" class="item">
                                Save &amp; Duplicate
                            </span>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <style>
        .loki-form .dropdown-menu {
            display: block;
        }
    </style>
</div>
