<?php
declare(strict_types=1);

/** @version 0.2.3 */

use Loki\AdminComponents\Form\Field\Field;
use Loki\CssUtils\Util\CssClass;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Form\FormViewModel;
use Loki\Components\Util\Block\ChildRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var Field $field */
/** @var FormViewModel $viewModel */
/** @var ChildRenderer $childRenderer */
/** @var CssClass $css */

$viewModel = $block->getViewModel();
$buttons = $viewModel->getButtons();
$mainSaveAction = false;
$otherSaveActions = [];
?>
<div class="<?= $css('page-main-actions') ?>">
    <div class="<?= $css('page-actions-placeholder', 'placeholder') ?>"></div>

    <div class="<?= $css('page-actions', 'actions') ?>">
        <div class="<?= $css('page-actions-inner', 'actions-inner') ?>">
            <div class="<?= $css('page-actions-buttons', 'actions-buttons') ?>">
                <?php foreach ($buttons as $button) : ?>
                    <?php $subButtons = $button->getSubButtons(); ?>
                    <button
                        @click="<?= $escaper->escapeHtml(
                            $button->getMethod()
                        ) ?>"
                        title="<?= $escaper->escapeHtml(
                            __($button->getLabel())
                        ) ?>"
                        type="button"
                        class="action- scalable <?= $escaper->escapeHtml(
                            $button->getCssClass()
                        ) ?>">
                        <span><?= $escaper->escapeHtml(
                                __($button->getLabel())
                            ) ?></span>
                    </button>
                <?php endforeach; ?>

                <?php if (!empty($otherSaveActions)) : ?>
                    <div
                        title="Save and Continue"
                        class="<?= $css(
                            'actions-split save primary', 'button-container'
                        ) ?>"
                    >
                        <button
                            @click="saveAndContinueAction"
                            title="Save and Continue"
                            class="<?= $css(
                                'action-default primary',
                                'button-save-and-continue'
                            ) ?>"
                        >
                            <span>Save and Continue</span>
                        </button>

                        <button @click="toggleOtherActions"
                                title="Save and Continue"
                                class="<?= $css(
                                    'action-toggle primary save',
                                    'button-toggle-actions'
                                ) ?>">
                            <span>Select</span>
                        </button>

                        <ul
                            class="<?= $css('dropdown-menu', 'listing') ?>"
                            x-cloak x-show="showOtherActions"
                        >
                            <?php foreach (
                                $otherSaveActions as $otherSaveAction
                            ): ?>
                                <li>
                                    <span
                                        @click="saveAndDuplicateAction"
                                        title="Save &amp; Duplicate"
                                        class="<?= $css(
                                            'item', 'action-label'
                                        ) ?>"
                                    >
                                        Save &amp; Duplicate
                                    </span>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <style>
        .loki-form .dropdown-menu {
            display: block;
        }
    </style>
</div>
