<?php
declare(strict_types=1);

/** @version 0.3.0 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<div class="entry-edit form-inline">
    <div class="fieldset-wrapper">
        <h1><?= $escaper->escapeHtml($block->getLabel()) ?></h1>

        <div class="admin__fieldset-wrapper-content">
            <fieldset class="admin__fieldset">
                <?= /* @noEscape */ $block->getChildHtml() ?>
            </fieldset>
        </div>
    </div>
</div>
