<?php
declare(strict_types=1);

/** @version 0.5.0 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Form\Field\Field;
use Loki\AdminComponents\ViewModel\FieldViewModel;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var Field $field */
/** @var TemplateRenderer $templateRenderer */
/** @var ViewModelFactory $viewModelFactory */

if (empty($templateRenderer)) {
    throw new RuntimeException(
        'Template renderer not found in block "'
        .$block->getNameInLayout()
        .'" [template "'.$block->getTemplate().'"]'
    );
}

$field = $block->getField();
if (false === $field instanceof Field) {
    $fieldViewModel = $viewModelFactory->create(FieldViewModel::class);
    $field = $fieldViewModel->getField($block);
}

if (false === $field->isVisible()) {
    return;
}

$depends = $field->getDepends();
$dependStatement = '';
if (!empty($depends)) {
    $dependStatement = 'x-show="item.'.$depends['propertyName'] . " == '".$depends['propertyValue']."'\"";
}
?>
<div class="admin__field" <?= $escaper->escapeHtml($dependStatement) ?>>
    <div class="admin__field-label">
        <label for="<?= $escaper->escapeHtml($field->getCode()) ?>">
            <span><?= $escaper->escapeHtml($field->getLabel()) ?></span>
            <?php if ($field->isRequired()): ?>
                <span style="color:red">*</span>
            <?php endif; ?>
        </label>
    </div>

    <div class="admin__field-control">
        <?= /* @noEscape */ $templateRenderer->html(
            $block,
            $field->getFieldType()->getTemplate(),
            ['field' => $field]
        ) ?>
    </div>
</div>
