<?php
declare(strict_types=1);

/** @version 0.4.0 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Form\Field\Field;
use Loki\AdminComponents\ViewModel\FieldViewModel;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var Field $field */
/** @var TemplateRenderer $templateRenderer */
/** @var ViewModelFactory $viewModelFactory */

if (empty($templateRenderer)) {
    throw new RuntimeException(
        'Template renderer not found in block "'
        .$block->getNameInLayout()
        .'" [template "'.$block->getTemplate().'"]'
    );
}

$field = $block->getField();
if (false === $field instanceof Field) {
    $fieldViewModel = $viewModelFactory->create(FieldViewModel::class);
    $field = $fieldViewModel->getField($block);
}
?>
<div class="admin__field">
    <div class="admin__field-label">
        <label for="<?= $escaper->escapeHtml($field->getCode()) ?>">
            <span><?= $escaper->escapeHtml($field->getLabel()) ?></span>
        </label>
    </div>

    <div class="admin__field-control">
        <?= /* @noEscape */ $templateRenderer->html(
            $block,
            $field->getFieldType()->getTemplate(),
            ['field' => $field]
        ) ?>
    </div>
</div>
