<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Form\Field\Field;
use Loki\AdminComponents\ViewModel\FieldViewModel;
use Yireo\LokiComponents\Factory\ViewModelFactory;
use Yireo\LokiComponents\Util\Block\TemplateRenderer;

/** @var Template $block */
/** @var Field $field */
/** @var TemplateRenderer $templateRenderer */
/** @var ViewModelFactory $viewModelFactory */

$field = $block->getField();
if (false === $field instanceof Field) {
    $fieldViewModel = $viewModelFactory->create(FieldViewModel::class);
    $field = $fieldViewModel->getField($block);
}

?>
<div class="admin__field">
    <div class="admin__field-label">
        <label for="<?= $field->getCode() ?>">
            <span><?= $field->getLabel() ?></span>
        </label>
    </div>

    <div class="admin__field-control">
        <?= $templateRenderer->html(
            $block,
            $field->getFieldType()->getTemplate(),
            ['field' => $field]
        ) ?>
    </div>
</div>
