<?php
declare(strict_types=1);

/** @version 0.7.2 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<div class="<?= $escaper->escapeHtml($css('entry-edit form-inline', '@todo')) ?>">
    <div class="<?= $escaper->escapeHtml($css('fieldset-wrapper', '@todo')) ?>">
        <h1><?= $escaper->escapeHtml($block->getLabel()) ?></h1>

        <div class="<?= $escaper->escapeHtml($css('admin__fieldset-wrapper-content', '@todo')) ?>">
            <fieldset class="<?= $escaper->escapeHtml($css('admin__fieldset', '@todo')) ?>">
                <?= /* @noEscape */ $block->getChildHtml() ?>
            </fieldset>
        </div>
    </div>
</div>
