<?php
declare(strict_types=1);

/** @version 0.2.6 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Ui\Button;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var Button $button */
$button = $block->getButton();
?>
<?php if ($button->getSubButtons()): ?>
    <div
        title="<?= $escaper->escapeHtml(__($button->getLabel())) ?>"
        class="actions-split <?= $escaper->escapeHtml(__($button->getCssClass())) ?>"
    >
        <button
            @click="<?= $escaper->escapeHtml(__($button->getMethod())) ?>"
            title="<?= $escaper->escapeHtml(__($button->getLabel())) ?>"
            <?php if ($button->getUrl()): ?>
                data-url="<?= /* @noEscape */ $button->getUrl() ?>"
            <?php endif; ?>
            class="action-default <?= $escaper->escapeHtml(__($button->getCssClass())) ?>"
        >
            <?= $escaper->escapeHtml(__($button->getLabel())) ?>
        </button>

        <button
            @click="toggleOtherActions"
            title="Toggle other actions"
            class="action-toggle <?= $escaper->escapeHtml(__($button->getCssClass())) ?>"
        >
            <span>Select</span>
        </button>

        <ul class="dropdown-menu" x-cloak x-show="showOtherActions">
            <?php foreach ($button->getSubButtons() as $subButton): ?>
                <li>
                    <span
                        @click="<?= $escaper->escapeHtml(__($subButton->getMethod())) ?>"
                        <?php if ($button->getUrl()): ?>
                            data-url="<?= /* @noEscape */ $button->getUrl() ?>"
                        <?php endif; ?>
                        title="<?= $escaper->escapeHtml(__($subButton->getLabel())) ?>"
                        class="item"
                    >
                    <?= $escaper->escapeHtml(__($subButton->getLabel())) ?>
                    </span>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

<?php else: ?>
    <button
        @click="<?= $escaper->escapeHtml($button->getMethod()) ?>"
        <?php if ($button->getUrl()): ?>
            data-url="<?= /* @noEscape */ $button->getUrl() ?>"
        <?php endif; ?>
        title="<?= $escaper->escapeHtml(__($button->getLabel())) ?>"
        type="button"
        class="scalable <?= $escaper->escapeHtml($button->getCssClass()) ?>"
    >
        <span><?= $escaper->escapeHtml(__($button->getLabel())) ?></span>
    </button>
<?php endif; ?>

<style>
    .actions-split .dropdown-menu {
        display: block;
    }
</style>
