<?php
declare(strict_types=1);

/** @version 0.6.0 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Form\FormViewModel;
use Loki\Components\Util\Block\BlockRenderer;
use Loki\Components\Util\Block\ChildRenderer;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var FormViewModel $viewModel */
/** @var BlockRenderer $blockRenderer */
/** @var ChildRenderer $childRenderer */
/** @var TemplateRenderer $templateRenderer */
if (!isset($viewModel)) {
    throw new RuntimeException('Did you make sure to declare the block "'.$block->getNameInLayout().'" as a Loki Component via "etc/loki_components.xml"?');
}
?>
<div class="loki-form form">
    <?= /* @noEscape */ $blockRenderer->html(
        $block,
        'loki-admin.form.actions',
        ['view_model' => $viewModel]
    ) ?>

    <div class="page-columns">
        <div class="main-col">
            <?= /* @noEscape */ $blockRenderer->html( $block, 'loki-admin.form.spinner') ?>
            <?= /* @noEscape */ $blockRenderer->html( $block, 'loki-admin.form.inner') ?>

            <div class="entry-edit form-inline">
                <div class="fieldset-wrapper">
                    <h1><?= $escaper->escapeHtml($block->getLabel()) ?></h1>

                    <?php foreach ($viewModel->getFieldsets() as $fieldset): ?>
                    <div class="admin__fieldset-wrapper-content">
                        <?php if ($fieldset->hasLabel()): ?>
                        <div class="fieldset-wrapper-title">
                            <strong class="admin__collapsible-title">
                                <?= $escaper->escapeHtml($fieldset->getLabel()) ?>
                            </strong>
                        </div>
                        <?php endif; ?>

                        <?php if ($fieldset->hasFields()): ?>
                        <fieldset class="admin__fieldset">
                            <?php foreach ($fieldset->getFields() as $field) : ?>
                                <?php if (false === $field->isVisible()) continue; ?>
                                <?= /* @noEscape */ $templateRenderer->html(
                                    $block,
                                    'Loki_AdminComponents::form/field.phtml',
                                    ['field' => $field]
                                ); ?>
                            <?php endforeach; ?>
                        </fieldset>
                        <?php endif; ?>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>

