<?php
declare(strict_types=1);

/** @version 0.2.3 */

use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Loki\Components\Util\Block\BlockRenderer;

/** @var Template $block */
/** @var GridViewModel $viewModel */
/** @var BlockRenderer $blockRenderer */

if (!isset($viewModel)) {
    throw new RuntimeException('Did you make sure to declare the block "'.$block->getNameInLayout().'" as a Loki Component via "etc/loki_components.xml"?');
}
?>
<div class="<?= $css('loki-grid grid', '@todo') ?>">
    <?php if ($viewModel->allowActions()): ?>
    <?= /* @noEscape */ $blockRenderer->html($block, 'loki-admin.grid.actions') ?>
    <?php endif; ?>

    <div class="<?= $css('page-columns', '@todo') ?>">
        <div class="<?= $css('main-col', '@todo') ?>">
            <div class="<?= $css('admin__data-grid-outer-wrap', '@todo') ?>">
                <?= /* @noEscape */ $blockRenderer->html($block, 'loki-admin.grid.spinner') ?>

                <div class="<?= $css('admin__data-grid-header', '@todo') ?>">
                    <div class="<?= $css('admin__data-grid-header-row', '@todo') ?>">
                        <?= /* @noEscape */ $blockRenderer->html($block, 'loki-admin.grid.filters') ?>
                    </div>
                    <div class="<?= $css('admin__data-grid-header-row', '@todo') ?>">
                        <?= /* @noEscape */ $blockRenderer->html($block, 'loki-admin.grid.search') ?>
                    </div>
                    <div class="<?= $css('admin__data-grid-header-row row row-gutter', '@todo') ?>">
                        <?= /* @noEscape */ $blockRenderer->html($block, 'loki-admin.grid.massactions') ?>
                        <?= /* @noEscape */ $blockRenderer->html($block, 'loki-admin.grid.pager') ?>
                        <?= /* @noEscape */ $blockRenderer->html($block, 'loki-admin.grid.records') ?>
                    </div>
                </div>

                <div class="<?= $css('admin__data-grid-header-row row row-gutter', '@todo') ?>">
                    <div class="<?= $css('col-xs-2', '@todo') ?>">
                        <div class="<?= $css('action-select-wrap', '@todo') ?>">
                            <?= /* @noEscape */ $blockRenderer->html($block, 'loki-admin.grid.row-actions') ?>
                        </div>
                    </div>
                </div>

                <?= /* @noEscape */ $blockRenderer->html($block, 'loki-admin.grid.table') ?>
            </div>
        </div>
    </div>
</div>
