<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Loki\Components\Component\ComponentViewModelInterface;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Loki\Components\Util\Block\TemplateRenderer;

/** @version 0.7.2 */
/** @var Escaper $escaper */
/** @var ComponentViewModelInterface $viewModel */
/** @var Template $block */
/** @var GridViewModel $viewModel */
/** @var TemplateRenderer $templateRenderer */

$viewModel = $block->getViewModel();
$buttons = $viewModel->getButtons();
?>
<div class="<?= $escaper->escapeHtml($css('page-main-actions', '@todo')) ?>">
    <div class="<?= $escaper->escapeHtml($css('page-actions', '@todo')) ?>">
        <div class="<?= $escaper->escapeHtml($css('page-actions-inner', '@todo')) ?>">
            <div class="<?= $escaper->escapeHtml($css('page-actions-buttons', '@todo')) ?>">
                <?php foreach ($buttons as $button): ?>
                    <?= /* @noEscape */ $templateRenderer->html(
                        $block,
                        'Loki_AdminComponents::ui/button.phtml',
                        ['button' => $button]
                    ) ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
