<?php
declare(strict_types=1);

/** @version 0.2.3 */

use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Template $block */
/** @var GridViewModel $viewModel */
/** @var TemplateRenderer $templateRenderer */

$viewModel = $block->getViewModel();
$buttons = $viewModel->getButtons();
?>
<div class="<?= $css('page-main-actions', '@todo') ?>">
    <div class="<?= $css('page-actions', '@todo') ?>">
        <div class="<?= $css('page-actions-inner', '@todo') ?>">
            <div class="<?= $css('page-actions-buttons', '@todo') ?>">
                <?php foreach ($buttons as $button): ?>
                    <?= /* @noEscape */ $templateRenderer->html(
                        $block,
                        'Loki_AdminComponents::ui/button.phtml',
                        ['button' => $button]
                    ) ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
