<?php
declare(strict_types=1);

/** @version 0.7.2 */

use Magento\Framework\Escaper;
use Magento\Framework\Data\Collection\AbstractDb;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var GridViewModel $viewModel */
/** @var TemplateRenderer $templateRenderer */

$viewModel = $block->getViewModel();
$availableColumns = $viewModel->getAvailableColumns();
$columns = $viewModel->getColumns();
$state = $viewModel->getState();
?>

<div class="<?= $escaper->escapeHtml($css('admin__action-dropdown-wrap admin__data-grid-action-columns', '@todo')) ?>">
    <button class="<?= $escaper->escapeHtml($css('admin__action-dropdown', '@todo')) ?>" type="button" @click="toggleColumnsSelector">
        <span class="<?= $escaper->escapeHtml($css('admin__action-dropdown-text', '@todo')) ?>">
            <?= $escaper->escapeHtml(__('Columns')) ?>
        </span>
    </button>
    <div class="<?= $escaper->escapeHtml($css('admin__action-dropdown-menu admin__data-grid-action-columns-menu _overflow', '@todo')) ?>" x-show="showColumnsSelector">
        <div class="<?= $escaper->escapeHtml($css('admin__action-dropdown-menu-header', '@todo')) ?>">
            <?= $escaper->escapeHtml(__(
                '%1 out of %1 visible',
                count($columns),
                count($availableColumns),
            )) ?>
        </div>
        <div class="<?= $escaper->escapeHtml($css('admin__action-dropdown-menu-content', '@todo')) ?>">
            <?php foreach($availableColumns as $name => $column): ?>
            <div class="<?= $escaper->escapeHtml($css('admin__field-option', '@todo')) ?>">
                <input
                    class="<?= $escaper->escapeHtml($css('admin__control-checkbox', '@todo')) ?>"
                    type="checkbox"
                    id="col-<?= $escaper->escapeHtml($column->getCode()) ?>"
                    data-column="<?= $escaper->escapeHtml($column->getCode()) ?>"
                    :checked="isColumnActive"
                    @change="toggleActiveColumn"
                >
                <label
                    class="<?= $escaper->escapeHtml($css('admin__field-label', '@todo')) ?>"
                    for="col-<?= $escaper->escapeHtml($column->getCode()) ?>">
                    <?= $escaper->escapeHtml($column->getLabel()) ?>
                </label>
            </div>
            <?php endforeach; ?>
        </div>
        <div class="<?= $escaper->escapeHtml($css('admin__action-dropdown-menu-footer', '@todo')) ?>">
            <div class="<?= $escaper->escapeHtml($css('admin__action-dropdown-footer-secondary-actions', '@todo')) ?>">
                <button class="<?= $escaper->escapeHtml($css('action-tertiary', '@todo')) ?>" type="button">
                    <?= $escaper->escapeHtml(__('Reset')) ?>
                </button>
            </div>
            <div class="<?= $escaper->escapeHtml($css('admin__action-dropdown-footer-main-actions', '@todo')) ?>">
                <button
                    class="<?= $escaper->escapeHtml($css('action-tertiary', '@todo')) ?>"
                    type="button"
                    @click="toggleColumnsSelector"
                >
                    <?= $escaper->escapeHtml(__('Cancel')) ?>
                </button>
            </div>
        </div>
    </div>
</div>

<style>
    .admin__data-grid-action-columns .admin__action-dropdown-menu {
        display: block;
        z-index: 2;
    }
</style>
