<?php
declare(strict_types=1);

/** @version 0.4.1 */

use Magento\Framework\Escaper;
use Magento\Framework\Data\Collection\AbstractDb;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var GridViewModel $viewModel */
/** @var TemplateRenderer $templateRenderer */

$viewModel = $block->getViewModel();
$availableColumns = $viewModel->getAvailableColumns();
$columns = $viewModel->getColumns();
$state = $viewModel->getState();
?>

<div class="admin__action-dropdown-wrap admin__data-grid-action-columns">
    <button class="admin__action-dropdown" type="button" @click="toggleColumnsSelector">
        <span class="admin__action-dropdown-text">
            <?= $escaper->escapeHtml(__('Columns')) ?>
        </span>
    </button>
    <div class="admin__action-dropdown-menu admin__data-grid-action-columns-menu _overflow" x-show="showColumnsSelector">
        <div class="admin__action-dropdown-menu-header">
            <?= $escaper->escapeHtml(__(
                '%1 out of %1 visible',
                count($columns),
                count($availableColumns),
            )) ?>
        </div>
        <div class="admin__action-dropdown-menu-content">
            <?php foreach($availableColumns as $name => $column): ?>
            <div class="admin__field-option">
                <input
                    class="admin__control-checkbox"
                    type="checkbox"
                    id="col-<?= $escaper->escapeHtml($column->getCode()) ?>"
                    data-column="<?= $escaper->escapeHtml($column->getCode()) ?>"
                    :checked="isColumnActive"
                    @change="toggleActiveColumn"
                >
                <label class="admin__field-label" for="col-<?= $escaper->escapeHtml($column->getCode()) ?>">
                    <?= $escaper->escapeHtml($column->getLabel()) ?>
                </label>
            </div>
            <?php endforeach; ?>
        </div>
        <div class="admin__action-dropdown-menu-footer">
            <div class="admin__action-dropdown-footer-secondary-actions">
                <button class="action-tertiary" type="button">
                    <?= $escaper->escapeHtml(__('Reset')) ?>
                </button>
            </div>
            <div class="admin__action-dropdown-footer-main-actions">
                <button class="action-tertiary" type="button" @click="toggleColumnsSelector">
                    <?= $escaper->escapeHtml(__('Cancel')) ?>
                </button>
            </div>
        </div>
    </div>
</div>

<style>
    .admin__data-grid-action-columns .admin__action-dropdown-menu {
        display: block;
        z-index: 2;
    }
</style>
