<?php
declare(strict_types=1);

/** @version 0.2.3 */

use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Template $block */
/** @var GridViewModel $viewModel */
/** @var TemplateRenderer $templateRenderer */

$viewModel = $block->getViewModel();
$filterFields = $viewModel->getFilterFields();
if (empty($filterFields)) {
    return;
}
?>
<div class="<?= $css('data-grid-filters-actions-wrap', '@todo') ?>">
    <div class="<?= $css('data-grid-filters-action-wrap', '@todo') ?>">
        <button :class="filterButtonClass" class="<?= $css('action-default', '@todo') ?>" @click="toggleFilters">
            Filters
        </button>
    </div>


</div>

<div x-cloak x-show="showFilters" class="<?= $css('admin__data-grid-filters-wrap _show', '@todo') ?>">
    <fieldset class="<?= $css('admin__fieldset admin__data-grid-filters', '@todo') ?>">
        <?php foreach ($filterFields as $filterField): ?>
            <fieldset class="<?= $css('admin__form-field', '@todo') ?>">
                <?= /* @noEscape */ $filterField->getBlock()->toHtml() ?>
            </fieldset>
        <?php endforeach; ?>

        <fieldset class="<?= $css('admin__form-field', '@todo') ?>">
            <legend class="<?= $css('admin__form-field-legend', '@todo') ?>">
                <span>ID</span>
            </legend>
            <div class="<?= $css('admin__form-field', '@todo') ?>">
                <label class="<?= $css('admin__form-field-label', '@todo') ?>">
                    <span>from</span>
                </label>
                <div class="<?= $css('admin__form-field-control', '@todo') ?>">
                    <input
                        class="<?= $css('admin__control-text', '@todo') ?>"
                        type="text"
                        name="entity_id[from]"
                        maxlength="255"
                    >
                </div>
            </div>
            <div class="<?= $css('admin__form-field', '@todo') ?>">
                <label class="<?= $css('admin__form-field-label', '@todo') ?>">
                    <span>to</span>
                </label>
                <div class="<?= $css('admin__form-field-control', '@todo') ?>">
                    <input
                        class="<?= $css('admin__control-text', '@todo') ?>"
                        type="text"
                        maxlength="255"
                    >
                </div>
            </div>
        </fieldset>
    </fieldset>

    <div class="<?= $css('admin__data-grid-filters-footer', '@todo') ?>">
        <div class="<?= $css('admin__footer-main-actions', '@todo') ?>">
            <button class="<?= $css('action-tertiary', '@todo') ?>" type="button" @click="toggleFilters">
                <span>Cancel</span>
            </button>
            <button class="<?= $css('action-secondary', '@todo') ?>" type="button" @click="applyFilters">
                <span>Apply Filters</span>
            </button>
        </div>
    </div>
</div>
