<?php
declare(strict_types=1);

/** @version 0.7.2 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Template $block */
/** @var GridViewModel $viewModel */
/** @var Escaper $escaper */
/** @var TemplateRenderer $templateRenderer */

$viewModel = $block->getViewModel();
$gridFilters = $viewModel->getGridFilters();
$gridFilterStates = $viewModel->getGridFilterStates();

if (empty($gridFilters)) {
    return;
}
?>
<div class="<?= $escaper->escapeHtml($css('data-grid-filters-actions-wrap', '@todo')) ?>">
    <div class="<?= $escaper->escapeHtml($css('data-grid-filters-action-wrap', '@todo')) ?>">
        <button :class="<?= $escaper->escapeHtml($css('filterButtonClass', '@todo')) ?>" class="<?= $escaper->escapeHtml($css('action-default', '@todo')) ?>" @click="toggleFilters">
            Filters
        </button>
    </div>
</div>

<?php if (!empty($gridFilterStates)): ?>
<div class="<?= $escaper->escapeHtml($css('admin__data-grid-filters-current _show', '@todo')) ?>">
    <div class="<?= $escaper->escapeHtml($css('admin__current-filters-title-wrap', '@todo')) ?>">
        <span class="<?= $escaper->escapeHtml($css('admin__current-filters-title', '@todo')) ?>">
            <?= $escaper->escapeHtml(__('Active filters:')) ?>
        </span>
    </div>
    <div class="<?= $escaper->escapeHtml($css('admin__current-filters-list-wrap', '@todo')) ?>">
        <ul class="<?= $escaper->escapeHtml($css('admin__current-filters-list', '@todo')) ?>" data-role="filter-list">
            <?php foreach ($gridFilterStates as $gridFilterState): ?>
            <li>
                <span class="<?= $escaper->escapeHtml($css('label', '@todo')) ?>"><?= $escaper->escapeHtml($gridFilterState->getField()) ?></span>
                <span class="<?= $escaper->escapeHtml($css('condition-type', '@todo')) ?>"><?= $escaper->escapeHtml($gridFilterState->getConditionType()) ?></span>
                <span class="<?= $escaper->escapeHtml($css('preview', '@todo')) ?>"><?= $escaper->escapeHtml($gridFilterState->renderValue()) ?></span>

                <button class="<?= $escaper->escapeHtml($css('action-remove', '@todo')) ?>" type="button" @click="removeFilter" data-field="<?= $escaper->escapeHtml($gridFilterState->getField()) ?>">
                    <span><?= $escaper->escapeHtml(__('Remove')) ?></span>
                </button>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>

<div x-cloak x-show="showFilters" class="<?= $escaper->escapeHtml($css('admin__data-grid-filters-wrap _show', '@todo')) ?>">
    <fieldset class="<?= $escaper->escapeHtml($css('admin__fieldset admin__data-grid-filters', '@todo')) ?>">
        <?php foreach ($gridFilters as $gridFilter): ?>
            <fieldset class="<?= $escaper->escapeHtml($css('admin__form-field', '@todo')) ?>">
                <?= /* @noEscape */ $gridFilter->render(); ?>
            </fieldset>
        <?php endforeach; ?>
    </fieldset>

    <div class="<?= $escaper->escapeHtml($css('admin__data-grid-filters-footer', '@todo')) ?>">
        <div class="<?= $escaper->escapeHtml($css('admin__footer-main-actions', '@todo')) ?>">
            <?php if (!empty($gridFilterStates)): ?>
            <button class="<?= $escaper->escapeHtml($css('action-tertiary', '@todo')) ?>" type="button" @click="clearFilters">
                <span><?= $escaper->escapeHtml(__('Clear all')) ?></span>
            </button>
            <?php endif; ?>

            <button class="<?= $escaper->escapeHtml($css('action-tertiary', '@todo')) ?>" type="button" data-action="grid-filter-cancel" @click="toggleFilters">
                <span><?= $escaper->escapeHtml(__('Cancel')) ?></span>
            </button>

            <button class="<?= $escaper->escapeHtml($css('action-secondary', '@todo')) ?>" type="button" data-action="grid-filter-apply" @click="applyFilters">
                <span><?= $escaper->escapeHtml(__('Apply Filters')) ?></span>
            </button>
        </div>
    </div>
</div>

