<?php
declare(strict_types=1);

/** @version 0.3.2 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Template $block */
/** @var GridViewModel $viewModel */
/** @var Escaper $escaper */
/** @var TemplateRenderer $templateRenderer */

$viewModel = $block->getViewModel();
$gridFilters = $viewModel->getGridFilters();
$gridFilterValues = $viewModel->getGridFilterValues();
if (empty($gridFilters)) {
    return;
}
?>
<div class="data-grid-filters-actions-wrap">
    <div class="data-grid-filters-action-wrap">
        <button :class="filterButtonClass" class="action-default" @click.prevent="toggleFilters">
            Filters
        </button>
    </div>
</div>

<?php if (!empty($gridFilterValues)): ?>
<div class="admin__data-grid-filters-current _show">
    <div class="admin__current-filters-title-wrap">
        <span class="admin__current-filters-title">
            <?= $escaper->escapeHtml(__('Active filters:')) ?>
        </span>
    </div>
    <div class="admin__current-filters-list-wrap">
        <ul class="admin__current-filters-list" data-role="filter-list">
            <?php foreach ($gridFilterValues as $gridFilterName => $gridFilterValue): ?>
            <li>
                <span class="label"><?= $escaper->escapeHtml($gridFilterName) ?></span>:
                <span class="preview"><?= $escaper->escapeHtml($gridFilterValue) ?></span>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>

<div x-cloak x-show="showFilters" class="admin__data-grid-filters-wrap _show">
    <fieldset class="admin__fieldset admin__data-grid-filters">
        <?php foreach ($gridFilters as $gridFilter): ?>
            <fieldset class="admin__form-field">
                <?= /* @noEscape */ $gridFilter->render(); ?>
            </fieldset>
        <?php endforeach; ?>
    </fieldset>

    <?php if (!empty($gridFilterValues)): ?>
    <div class="admin__data-grid-filters-footer">
        <div class="admin__footer-main-actions">
            <button class="action-tertiary" type="button" @click="toggleFilters">
                <span>Clear all filters</span>
            </button>
        </div>
    </div>
    <?php endif; ?>
</div>
