<?php
declare(strict_types=1);

/** @version 0.2.3 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var GridViewModel $viewModel */
/** @var TemplateRenderer $templateRenderer */

$viewModel = $block->getViewModel();
$massActions = $viewModel->getMassActions();
if (empty($massActions)) {
    return;
}
?>
<div class="<?= $css('col-xs-2', '@todo') ?>">
    <div class="<?= $css('action-select-wrap', '@todo') ?>">
        <button class="<?= $css('action-select', '@todo') ?>" title="Select Items" @click="toggleMassActions">
            <span>Actions</span>
        </button>
        <div class="<?= $css('action-menu-items', '@todo') ?>" x-cloak x-show="showMassActions" style="z-index:300">
            <ul class="<?= $css('action-menu', '@todo') ?>">
                <?php foreach ($massActions as $massAction): ?>
                    <li @click="massAction" data-url="<?= /* @noEscape */ $massAction->getUrl() ?>">
                        <span class="<?= $css('action-menu-item', '@todo') ?>"><?= $escaper->escapeHtml($massAction->getLabel()) ?></span>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <form method="post" x-ref="massActionForm">
        <input type="hidden" name="selected[]" x-ref="massActionFormIds" />
        <input type="hidden" name="namespace" value="<?= $escaper->escapeHtml($viewModel->getNamespace()) ?>" />
        <input type="hidden" name="loki_redirect_url" value="<?= /* @noEscape */ $viewModel->getIndexUrl() ?>" />
        <?php echo /* @noEscape */ $block->getBlockHtml('formkey') ?>
    </form>
</div>
