<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Yireo\LokiComponents\Util\Block\TemplateRenderer;

/** @var Template $block */
/** @var GridViewModel $viewModel */
/** @var TemplateRenderer $templateRenderer */

$viewModel = $block->getViewModel();
$massActions = $viewModel->getMassActions();
if (empty($massActions)) {
    return;
}
?>
<div class="col-xs-2">
    <div class="action-select-wrap">
        <button class="action-select" title="Select Items" @click="toggleMassActions">
            <span>Actions</span>
        </button>
        <div class="action-menu-items" x-cloak x-show="showMassActions" style="z-index:300">
            <ul class="action-menu">
                <?php foreach ($massActions as $massAction): ?>
                    <li @click="massAction" data-url="<?= $massAction->getUrl() ?>">
                        <span class="action-menu-item"><?= $massAction->getLabel() ?></span>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <form method="post" x-ref="massActionForm">
        <input type="hidden" name="selected[]" x-ref="massActionFormIds" />
        <input type="hidden" name="namespace" value="<?= $viewModel->getNamespace() ?>" />
        <input type="hidden" name="loki_redirect_url" value="<?= $viewModel->getIndexUrl() ?>" />
        <?php echo $block->getBlockHtml('formkey') ?>
    </form>
</div>
