<?php
declare(strict_types=1);

/** @version 0.6.1 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var GridViewModel $viewModel */
/** @var TemplateRenderer $templateRenderer */

$viewModel = $block->getViewModel();
$massActions = $viewModel->getMassActions();
if (empty($massActions)) {
    return;
}
?>
<div class="col-xs-2">
    <div class="action-select-wrap">
        <button class="action-select" title="Select Items" @click.prevent="toggleMassActions">
            <span>Actions</span>
        </button>

        <div class="action-menu-items" x-cloak x-show="showMassActions" style="z-index:300">
            <ul class="action-menu">
                <?php foreach ($massActions as $massAction): ?>
                    <li @click.prevent="massAction" data-url="<?= /* @noEscape */ $massAction->getUrl() ?>">
                        <span class="action-menu-item"><?= $escaper->escapeHtml($massAction->getLabel()) ?></span>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <form method="post" x-ref="massActionForm">
        <input type="hidden" name="selected[]" x-ref="massActionFormIds" />
        <input type="hidden" name="namespace" value="<?= $escaper->escapeHtml($viewModel->getNamespace()) ?>" />
        <input type="hidden" name="loki_redirect_url" value="<?= /* @noEscape */ $viewModel->getCurrentUrl() ?>" />
        <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
    </form>
</div>
