<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Loki\Components\Util\Block\ChildRenderer;

/** @var Template $block */
/** @var ChildRenderer $childRenderer */
/** @var GridViewModel $viewModel */
$viewModel = $block->getViewModel();
?>
<div class="admin__data-grid-pager-wrap">
    <?= $childRenderer->html($block, 'limit') ?>
    <?= $childRenderer->html($block, 'pagination') ?>
</div>
