<?php
declare(strict_types=1);

/** @version 0.7.2 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Loki\Components\Util\Block\ChildRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ChildRenderer $childRenderer */
/** @var GridViewModel $viewModel */
$viewModel = $block->getViewModel();
?>
<div class="<?= $escaper->escapeHtml($css('admin__data-grid-pager-wrap', '@todo')) ?>">
    <?= /* @noEscape */ $childRenderer->html($block, 'limit') ?>
    <?= /* @noEscape */ $childRenderer->html($block, 'pagination') ?>
</div>
