<?php
declare(strict_types=1);

/** @version 0.4.1 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
?>
<div class="admin__control-support-text">
    <span x-html="totalItems"></span> <?= $escaper->escapeHtml(__('records found')) ?>

    <span x-cloak x-show="getSelectedIdCount">
        (<span x-html="getSelectedIdCount"></span> selected)
    </span>
</div>
