<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 0.7.2 */
/** @var Escaper $escaper */
/** @var Template $block */
?>
<div class="<?= $escaper->escapeHtml($css('admin__control-support-text', '@todo')) ?>">
    <span x-text="totalItems"></span> <?= $escaper->escapeHtml(__('records found')) ?>

    <span x-cloak x-show="getSelectedIdCount">
        (<span x-text="getSelectedIdCount"></span> selected)
    </span>
</div>
