<?php
declare(strict_types=1);

/** @version 0.7.2 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var GridViewModel $viewModel */

$viewModel = $block->getViewModel();
$searchableFields = $viewModel->getSearchableFields();
if (empty($searchableFields)) {
    echo '<!-- No searchable fields found -->';
    return;
}
?>
<div class="<?= $escaper->escapeHtml($css('data-grid-search-control-wrap', '@todo')) ?>">
    <label class="<?= $escaper->escapeHtml($css('data-grid-search-label', '@todo')) ?>" title="Search" for="grid-search">
        <span><?= $escaper->escapeHtml(__('Search')) ?></span>
    </label>
    <input
        :value="search"
        @change="changeSearch"
        id="grid-search"
        class="<?= $escaper->escapeHtml($css('admin__control-text data-grid-search-control', '@todo')) ?>"
        type="text"
        placeholder="<?= $escaper->escapeHtml(__('Search by keyword')) ?>"
        aria-label="<?= $escaper->escapeHtml(__('Search by keyword')) ?>"
    />
    <button :click="changeSearch" class="<?= $escaper->escapeHtml($css('action-submit', '@todo')) ?>" type="button" aria-label="<?= $escaper->escapeHtml(__('Search' ))?>">
        <span><?= $escaper->escapeHtml(__('Search' ))?></span>
    </button>
</div>
