<?php
declare(strict_types=1);
?>
<div class="data-grid-search-control-wrap">
    <label class="data-grid-search-label" title="Search" for="grid-search">
        <span><?= __('Search') ?></span>
    </label>
    <input
        :value="search"
        @change="changeSearch"
        id="grid-search"
        class="admin__control-text data-grid-search-control"
        type="text"
        placeholder="<?= __('Search by keyword') ?>"
        aria-label="<?= __('Search by keyword') ?>"
    />
    <button :click="changeSearch" class="action-submit" type="button" aria-label="<?= __('Search' )?>">
        <span><?= __('Search' )?></span>
    </button>
</div>
