<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiAdminComponents\Component\Grid\GridViewModel;
use Yireo\LokiComponents\Util\Block\TemplateRenderer;

/** @var Template $block */
/** @var GridViewModel $viewModel */
/** @var TemplateRenderer $templateRenderer */

$viewModel = $block->getViewModel();
?>
<div class="admin__data-grid-wrap" data-role="grid-wrapper">
    <table class="data-grid" data-role="grid">
        <thead>
        <tr x-sort.ghost="repositionColumns">
            <?php
            $i = 1;
            foreach ($viewModel->getColumns() as $code => $label): ?>
                <th class="data-grid-th" x-sort:item="'<?= $viewModel->getJsComponentId() ?>.<?= $code ?>'">
                    <span class="data-grid-cell-content"><?= __($label) ?></span>
                </th>
                <?php
                $i++;
            endforeach; ?>
            <?php if ($viewModel->allowActions()): ?>
            <th class="data-grid-th">
                <span class="data-grid-cell-content"><?= __('Actions') ?></span>
            </th>
            <?php endif; ?>
        </tr>
        </thead>
        <tbody>
        <?php $i = 0; ?>
        <?php foreach ($viewModel->getItems() as $item): ?>
            <?php $cellActions = $viewModel->getCellActions($item); ?>
            <?php $trClass = ($i % 2 === 1) ? '_odd-row' : '_even-row'; ?>
            <tr class="data-row <?= $trClass ?>">
                <?php foreach ($viewModel->getColumns() as $propertyName => $label): ?>
                    <td class="data-grid-cell">
                        <div class="data-grid-cell-content">
                            <?php $cellTemplate = $viewModel->getCellTemplate($item, $propertyName) ?>
                            <?php $value = $viewModel->getValueFromItem($item, $propertyName); ?>
                            <?= $templateRenderer->html($block, $cellTemplate, [
                                'item' => $item,
                                'value' => $value,
                                'column_name' => $propertyName,
                            ]) ?>
                        </div>
                    </td>
                <?php endforeach; ?>
                <?php if ($viewModel->allowActions()): ?>
                <td class="data-grid-cell">
                    <div class="data-grid-cell-content">
                        <ul>
                            <?php foreach ($cellActions as $cellAction): ?>
                                <li>
                                    <a href="<?= $cellAction->getUrl() ?>"><?= $cellAction->getLabel() ?></a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </td>
                <?php endif; ?>
            </tr>
            <?php $i++; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
