<?php
declare(strict_types=1);

/** @version 0.2.3 */

use Magento\Framework\Escaper;
use Magento\Framework\Data\Collection\AbstractDb;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var GridViewModel $viewModel */
/** @var TemplateRenderer $templateRenderer */

$viewModel = $block->getViewModel();
$state = $viewModel->getState();
?>
<div class="<?= $css('admin__data-grid-wrap') ?>" data-role="grid-wrapper">
    <table class="<?= $css('data-grid', 'table') ?>" data-role="grid">
        <thead>
        <tr x-sort.ghost="repositionColumns">
            <th class="<?= $css('data-grid-multicheck-cell', 'multicheck-heading') ?>">
                <div class="<?= $css('action-multicheck-wrap', 'multicheck-inner') ?>">
                    <input
                        class="<?= $css('admin__control-checkbox', 'multicheck-checkbox') ?>"
                        type="checkbox"
                        disabled
                    />

                    <button
                        class="<?= $css('action-multicheck-toggle', 'multicheck-button') ?>"
                        @click="toggleSelectedMenu"
                    >
                        <span>Options</span>
                    </button>

                    <ul class="<?= $css('action-menu', 'listing') ?>" x-cloak x-show="showSelectedMenu">
                        <li @click="selectAll">
                            <span class="<?= $css('action-menu-item', 'item-span') ?>">Select All</span>
                        </li>

                        <li @click="deselectAll">
                            <span class="<?= $css('action-menu-item', 'item-span') ?>">Deselect All</span>
                        </li>

                        <li @click="selectAllOnPage">
                            <span class="<?= $css('action-menu-item', 'item-span') ?>">Select All on This Page</span>
                        </li>

                        <li @click="deselectAllOnPage">
                            <span class="<?= $css('action-menu-item', 'item-span') ?>">Deselect All on This Page</span>
                        </li>
                    </ul>
                </div>
            </th>
            <?php
            $i = 1;
            foreach ($viewModel->getColumns() as $columnName => $label): ?>
                <?php if ($columnName === 'ids') {
                    continue;
                } ?>
                <?php
                $additionalCss = '';
                if ($columnName === $state->getSortBy()) {
                    $additionalCss .= $state->getSortDirection(
                    ) === AbstractDb::SORT_ORDER_ASC ? '_ascend' : '_descend';
                }
                ?>
                <th
                    class="data-grid-th _sortable <?= $escaper->escapeHtml($additionalCss) ?>"
                    data-column="<?= $escaper->escapeHtml($columnName) ?>"
                    @click="sortColumn"
                    x-sort:item="'<?= $escaper->escapeHtml($viewModel->getJsComponentId()) ?>.<?= $escaper->escapeHtml($columnName) ?>'">
                    <span class="<?= $css('data-grid-cell-content', 'heading-span') ?>"><?= $escaper->escapeHtml(__($label)) ?></span>
                </th>
                <?php
                $i++;
            endforeach; ?>
            <?php if ($viewModel->allowActions()): ?>
                <th class="<?= $css('data-grid-th', 'heading') ?>">
                    <span class="<?= $css('pointer data-grid-cell-content', 'heading-span') ?>"><?= $escaper->escapeHtml(__('Actions')) ?></span>
                </th>
            <?php endif; ?>
        </tr>
        </thead>
        <tbody>
        <?php $i = 0; ?>
        <?php foreach ($viewModel->getItems() as $item): ?>
            <?php $cellActions = $viewModel->getCellActions($item); ?>
            <?php $trClass = ($i % 2 === 1) ? '_odd-row' : '_even-row'; ?>
            <tr class="data-row <?= $escaper->escapeHtml($trClass) ?>">
                <td class="<?= $css('data-grid-checkbox-cell', '@todo') ?>">
                    <label class="<?= $css('data-grid-checkbox-cell-inner', '@todo') ?>">
                        <input
                            class="<?= $css('admin__control-checkbox', '@todo') ?>"
                            type="checkbox"
                            :checked="isSelected"
                            @change="toggleSelectedId"
                            data-row-id="<?= $escaper->escapeHtml($item->getId()) ?>">
                        <label></label>
                    </label>
                </td>
                <?php foreach ($viewModel->getColumns() as $columnName => $label): ?>
                    <?php if ($columnName === 'ids') {
                        continue;
                    } ?>
                    <td class="<?= $css('data-grid-cell', '@todo') ?>">
                        <div class="<?= $css('data-grid-cell-content', '@todo') ?>">
                            <?php $cellTemplate = $viewModel->getCellTemplate($item, $columnName) ?>
                            <?php $value = $viewModel->getValueFromItem($item, $columnName); ?>
                            <?= /* @noEscape */ $templateRenderer->html($block, $cellTemplate, [
                                'item' => $item,
                                'value' => $value,
                                'column_name' => $columnName,
                            ]) ?>
                        </div>
                    </td>
                <?php endforeach; ?>
                <?php if ($viewModel->allowActions()): ?>
                    <td class="<?= $css('data-grid-cell', '@todo') ?>">
                        <div class="<?= $css('data-grid-cell-content', '@todo') ?>">
                            <ul>
                                <?php foreach ($cellActions as $cellAction): ?>
                                    <li>
                                        <a href="<?= /* @noEscape */ $cellAction->getUrl() ?>"><?= $escaper->escapeHtml($cellAction->getLabel()) ?></a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </td>
                <?php endif; ?>
            </tr>
            <?php $i++; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<style>
    .action-menu {
        display: block;
    }

    .loki-grid .data-grid .data-grid-th._sortable {
        z-index: auto;
    }
</style>
