<?php
declare(strict_types=1);

use Magento\Framework\Data\Collection\AbstractDb;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Yireo\LokiComponents\Util\Block\TemplateRenderer;

/** @var Template $block */
/** @var GridViewModel $viewModel */
/** @var TemplateRenderer $templateRenderer */

$viewModel = $block->getViewModel();
$state = $viewModel->getState();
?>
<div class="admin__data-grid-wrap" data-role="grid-wrapper">
    <table class="data-grid" data-role="grid">
        <thead>
        <tr x-sort.ghost="repositionColumns">
            <th class="data-grid-multicheck-cell">
                <div class="action-multicheck-wrap">
                    <input class="admin__control-checkbox" type="checkbox" disabled>
                    <button class="action-multicheck-toggle" @click="toggleSelectedMenu">
                        <span>Options</span>
                    </button>
                    <ul class="action-menu" x-cloak x-show="showSelectedMenu">
                        <li @click="selectAll">
                            <span class="action-menu-item">Select All</span>
                        </li>

                        <li @click="deselectAll">
                            <span class="action-menu-item">Deselect All</span>
                        </li>

                        <li @click="selectAllOnPage">
                            <span class="action-menu-item">Select All on This Page</span>
                        </li>

                        <li @click="deselectAllOnPage">
                            <span class="action-menu-item">Deselect All on This Page</span>
                        </li>
                    </ul>
                </div>
            </th>
            <?php
            $i = 1;
            foreach ($viewModel->getColumns() as $columnName => $label): ?>
                <?php if ($columnName === 'ids') {
                    continue;
                } ?>
                <?php
                $additionalCss = '';
                if ($columnName === $state->getSortBy()) {
                    $additionalCss .= $state->getSortDirection(
                    ) === AbstractDb::SORT_ORDER_ASC ? '_ascend' : '_descend';
                }
                ?>
                <th
                    class="data-grid-th _sortable <?= $additionalCss ?>"
                    data-column="<?= $columnName ?>"
                    @click="sortColumn"
                    x-sort:item="'<?= $viewModel->getJsComponentId() ?>.<?= $columnName ?>'">
                    <span class="data-grid-cell-content"><?= __($label) ?></span>
                </th>
                <?php
                $i++;
            endforeach; ?>
            <?php if ($viewModel->allowActions()): ?>
                <th class="data-grid-th">
                    <span class="pointer data-grid-cell-content"><?= __('Actions') ?></span>
                </th>
            <?php endif; ?>
        </tr>
        </thead>
        <tbody>
        <?php $i = 0; ?>
        <?php foreach ($viewModel->getItems() as $item): ?>
            <?php $cellActions = $viewModel->getCellActions($item); ?>
            <?php $trClass = ($i % 2 === 1) ? '_odd-row' : '_even-row'; ?>
            <tr class="data-row <?= $trClass ?>">
                <td class="data-grid-checkbox-cell">
                    <label class="data-grid-checkbox-cell-inner">
                        <input
                            class="admin__control-checkbox"
                            type="checkbox"
                            :checked="isSelected"
                            @change="toggleSelectedId"
                            data-row-id="<?= $item->getId() ?>">
                        <label></label>
                    </label>
                </td>
                <?php foreach ($viewModel->getColumns() as $columnName => $label): ?>
                    <?php if ($columnName === 'ids') {
                        continue;
                    } ?>
                    <td class="data-grid-cell">
                        <div class="data-grid-cell-content">
                            <?php $cellTemplate = $viewModel->getCellTemplate($item, $columnName) ?>
                            <?php $value = $viewModel->getValueFromItem($item, $columnName); ?>
                            <?= $templateRenderer->html($block, $cellTemplate, [
                                'item' => $item,
                                'value' => $value,
                                'column_name' => $columnName,
                            ]) ?>
                        </div>
                    </td>
                <?php endforeach; ?>
                <?php if ($viewModel->allowActions()): ?>
                    <td class="data-grid-cell">
                        <div class="data-grid-cell-content">
                            <ul>
                                <?php foreach ($cellActions as $cellAction): ?>
                                    <li>
                                        <a href="<?= $cellAction->getUrl() ?>"><?= $cellAction->getLabel() ?></a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </td>
                <?php endif; ?>
            </tr>
            <?php $i++; ?>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<style>
    .action-menu {
        display: block;
    }

    .loki-grid .data-grid .data-grid-th._sortable {
        z-index: auto;
    }
</style>
