<?php
declare(strict_types=1);

use Magento\Framework\Escaper;

/** @version 0.7.2 */
/** @var Escaper $escaper */

?>
<div class="<?= $escaper->escapeHtml($css('admin__action-dropdown-wrap admin__data-grid-action-bookmarks', '@todo')) ?>">
    <button class="<?= $escaper->escapeHtml($css('admin__action-dropdown', '@todo')) ?>" type="button" @click="toggleViewSelector">
        <span class="<?= $escaper->escapeHtml($css('admin__action-dropdown-text', '@todo')) ?>"><?= $escaper->escapeHtml(__('Default View')) ?></span>
    </button>
    <ul class="<?= $escaper->escapeHtml($css('admin__action-dropdown-menu', '@todo')) ?>" x-show="showViewSelector">
        <li>
            <div class="<?= $escaper->escapeHtml($css('action-dropdown-menu-item', '@todo')) ?>">
                <a class="<?= $escaper->escapeHtml($css('action-dropdown-menu-link', '@todo')) ?>"><?= $escaper->escapeHtml(__('Default View')) ?></a>
            </div>
        </li>

        <li class="<?= $escaper->escapeHtml($css('action-dropdown-menu-action action-dropdown-menu-item-last', '@todo')) ?>" style="display: none;">
            <a href=""><?= $escaper->escapeHtml(__('Save View As...')) ?></a>
            <div class="<?= $escaper->escapeHtml($css('action-dropdown-menu-item-edit', '@todo')) ?>" style="display: none;">
                <input id="new-view" class="<?= $escaper->escapeHtml($css('admin__control-text', '@todo')) ?>" type="text" aria-label="<?= $escaper->escapeHtml(__('New View')) ?>">
                <div class="<?= $escaper->escapeHtml($css('action-dropdown-menu-item-actions', '@todo')) ?>">
                    <button class="<?= $escaper->escapeHtml($css('action-submit', '@todo')) ?>" type="button" title="<?= $escaper->escapeHtml(__('Save all changes')) ?>">
                        <span><?= $escaper->escapeHtml(__('Submit')) ?></span>
                    </button>
                </div>
            </div>
        </li>
    </ul>
</div>

<style>
    .admin__data-grid-action-bookmarks .admin__action-dropdown-menu {
        display: block;
        z-index: 1;
    }
</style>
