<?php
declare(strict_types=1);

/** @version 0.7.2 */
?>
<div class="admin__action-dropdown-wrap admin__data-grid-action-bookmarks">
    <button class="admin__action-dropdown" type="button" @click="toggleViewSelector">
        <span class="admin__action-dropdown-text"><?= __('Default View') ?></span>
    </button>
    <ul class="admin__action-dropdown-menu" x-show="showViewSelector">
        <li>
            <div class="action-dropdown-menu-item">
                <a class="action-dropdown-menu-link"><?= __('Default View') ?></a>
            </div>
        </li>

        <li class="action-dropdown-menu-action action-dropdown-menu-item-last" style="display: none;">
            <a href=""><?= __('Save View As...') ?></a>
            <div class="action-dropdown-menu-item-edit" style="display: none;">
                <input id="new-view" class="admin__control-text" type="text" aria-label="<?= __('New View') ?>">
                <div class="action-dropdown-menu-item-actions">
                    <button class="action-submit" type="button" title="<?= __('Save all changes') ?>">
                        <span><?= __('Submit') ?></span>
                    </button>
                </div>
            </div>
        </li>
    </ul>
</div>

<style>
    .admin__data-grid-action-bookmarks .admin__action-dropdown-menu {
        display: block;
        z-index: 1;
    }
</style>
