<?php
declare(strict_types=1);

/** @version 0.5.0 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    const LokiAdminFormComponentType = {
        ...LokiComponentType,
        showOtherActions: false,
        toggleOtherActions() {
            this.showOtherActions = !this.showOtherActions;
        },
        closeAction() {
            window.location.href = this.indexUrl;
        },
        saveAndContinueAction() {
            this.post({
                actions: ['save'],
                item: this.item,
            });
        },
        saveAndDuplicateAction() {
            this.post({
                actions: ['save', 'duplicate'],
                item: this.item,
            });

            this.closeAction();
        },
        saveAndCloseAction() {
            this.post({
                actions: ['save'],
                item: this.item,
            });

            this.closeAction();
        },
        deleteAction() {
            this.post({
                actions: ['delete'],
                item: this.item,
            });

            this.closeAction();
        },
        setValue(event) {
            let propertyValue;
            if (event.target.tagName.toLowerCase() === 'select' && event.target.multiple) {
                propertyValue = [];
                Object.values(event.target.options).forEach((option) => {
                    if (option.selected) {
                        propertyValue.push(option.value);
                    }
                })
            } else {
                propertyValue = event.target.value;
            }

            const propertyName = event.target.getAttribute('data-name');
            this.item[propertyName] = propertyValue;
        },
        toggleValueByClick(event) {
            const propertyName = event.target.getAttribute('data-name');
            this.item[propertyName] =  !this.item[propertyName];;
        }
    }
</script>
