<?php
declare(strict_types=1);

/** @version 0.3.0 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    const LokiAdminGridComponentType = {
        ...LokiAdminPaginationComponentPartial,
        ...LokiAdminLimitComponentPartial,
        ...LokiAdminInlineEditComponentPartial,
        ...LokiAdminSelectedComponentPartial,
        ...LokiAdminFiltersComponentPartial,
        ...LokiAdminMassActionsComponentPartial,
        ...LokiComponentType,
        columnPositions: {},
        showOtherActions: false,
        toggleOtherActions() {
            this.showOtherActions = !this.showOtherActions;
        },
        sortColumn(event) {
            if (!event) {
                return;
            }

            this.post({
                sort: {
                    sortBy: this.$el.getAttribute('data-column'),
                    sortDirection: this.sortDirection === 'ASC' ? 'DESC' : 'ASC',
                }
            });
        },
        newUrl: '',
        newAction() {
            window.location.href = this.newUrl;
        },
        redirectAction() {
            window.location.href = this.$el.getAttribute('data-url');
        },
        changeSearch(event) {
            if (!event) {
                return;
            }

            this.post({search: this.$el.value});
        },

    }
</script>
