<script>
    const LokiAdminGridComponentType = {
        ...LokiAdminPaginationComponentPartial,
        ...LokiAdminLimitComponentPartial,
        ...LokiAdminInlineEditComponentPartial,
        ...LokiComponentType,
        columns: {},
        newAction() {
            window.location.href = this.newUrl;
        },
        changeSearch(event) {
            if (!event) {
                return;
            }
            this.post({search: event.target.value});
        },
        sortColumns(item, position) {
            console.log('Sorting columns', item, position, this.$item, this.$position, this.columns);
        }
    }
</script>
