<?php
declare(strict_types=1);

/** @version 0.3.3 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    const LokiAdminGridComponentType = {
        ...LokiAdminPaginationComponentPartial,
        ...LokiAdminLimitComponentPartial,
        ...LokiAdminInlineEditComponentPartial,
        ...LokiAdminSelectedComponentPartial,
        ...LokiAdminFiltersComponentPartial,
        ...LokiAdminMassActionsComponentPartial,
        ...LokiComponentType,
        columnPositions: {},
        showOtherActions: false,
        gridFilters: {},
        toggleOtherActions() {
            this.showOtherActions = !this.showOtherActions;
        },
        setGridFilter(event) {
            const value = event.target.value;
            const name = event.target.name;
            this.gridFilters[name] = value;

            this.post({
                filter: {
                    name: name,
                    value: value,
                }
            });
        },
        clearFilters() {
            this.post({
                clearFilters: true
            });
        },
        removeFilter() {
            const targetFilter = this.$el.getAttribute('data-field');
            if (!targetFilter) {
                return;
            }

            this.post({
                removeFilter: targetFilter
            });
        },
        sortColumn(event) {
            if (!event) {
                return;
            }

            this.post({
                sort: {
                    sortBy: this.$el.getAttribute('data-column'),
                    sortDirection: this.sortDirection === 'ASC' ? 'DESC' : 'ASC',
                }
            });
        },
        newUrl: '',
        newAction() {
            window.location.href = this.newUrl;
        },
        redirectAction() {
            window.location.href = this.$el.getAttribute('data-url');
        },
        changeSearch(event) {
            if (!event) {
                return;
            }

            this.post({search: this.$el.value});
        },

    }
</script>
