<?php
declare(strict_types=1);

/** @version 0.2.8 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var GridViewModel $viewModel */
$viewModel = $block->getViewModel();

$limits = [5, 10, 20, 30, 50, 100, 200]; // @todo: Move this into a viewModel
$totalPages = $viewModel->getTotalPages();
$page = $viewModel->getPage();
?>
<div style="display: inline-block">
    <div class="selectmenu">
        <div class="selectmenu-value">
            <input :value="limit" @change="changeLimit" type="text" aria-labelledby="per-page-text"
                   id="product_listing.product_listing.listing_top.listing_paging_sizes">
        </div>

        <button @click="toggleLimitOptions" class="selectmenu-toggle" type="button"
                aria-labelledby="per-page-text select-button-text">
            <span id="select-button-text"><?= $escaper->escapeHtml(__('Select')) ?></span>
        </button>

        <div x-cloak x-show="showLimitOptions" class="selectmenu-items" style="z-index:1001">
            <ul>
                <?php foreach ($limits as $limit): ?>
                    <li>
                        <div class="selectmenu-item">
                            <button
                                @click="setLimitFromElement"
                                data-limit="<?= $escaper->escapeHtml($limit) ?>"
                                class="selectmenu-item-action"
                                type="button">
                                <?= $escaper->escapeHtml($limit) ?>
                            </button>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>

    <label class="admin__control-support-text" id="per-page-text"
           for="product_listing.product_listing.listing_top.listing_paging_sizes"><?= $escaper->escapeHtml(__('per page')) ?></label>

    <style>
        .loki-grid .selectmenu-items {
            display: block;
        }
    </style>
</div>
