<?php
declare(strict_types=1);

use Loki\Components\Component\ComponentViewModelInterface;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;

/** @version 0.7.2 */
/** @var ComponentViewModelInterface $viewModel */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var GridViewModel $viewModel */

$viewModel = $block->getViewModel();
$totalPages = $viewModel->getTotalPages();
$page = $viewModel->getPage();
?>
<div class="<?= $escaper->escapeHtml($css('admin__data-grid-pager', '@todo')) ?>">
    <button
        @click.prevent="previousPage"
        class="<?= $escaper->escapeHtml($css('action-previous', '@todo')) ?>"
        type="button"
        title="<?= $escaper->escapeHtml(__('Previous Page')) ?>"
        <?= ($page < 2) ? 'disabled' : '' ?>></button>

    <input
        :value="page"
        @change="changePage"
        class="<?= $escaper->escapeHtml($css('admin__control-text', '@todo')) ?>"
        type="number"
        id="current_page"/>

    <label class="<?= $escaper->escapeHtml($css('admin__control-support-text', '@todo')) ?>" for="current_page">
        of <span x-text="totalPages"></span> pages
    </label>

    <button
        @click.prevent="nextPage"
        class="<?= $escaper->escapeHtml($css('action-next', '@todo')) ?>"
        type="button"
        title="<?= $escaper->escapeHtml(__('Next Page')) ?>"
        <?= ($page >= $totalPages) ? 'disabled' : '' ?>></button>
</div>
