<?php
declare(strict_types=1);

/** @version 0.6.0 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Component\Grid\GridViewModel;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var GridViewModel $viewModel */
$viewModel = $block->getViewModel();

$limits = [5, 10, 20, 30, 50, 100, 200]; // @todo: Move this into a viewModel
$totalPages = $viewModel->getTotalPages();
$page = $viewModel->getPage();
?>
<div class="admin__data-grid-pager">
    <button
        @click.prevent="previousPage"
        class="action-previous"
        type="button"
        title="<?= $escaper->escapeHtml(__('Previous Page')) ?>"
        <?= ($page < 2) ? 'disabled' : '' ?>></button>

    <input
        :value="page"
        @change="changePage"
        class="admin__control-text"
        type="number"
        id="current_page"/>

    <label class="admin__control-support-text" for="current_page">
        of <span x-html="totalPages"></span> pages
    </label>

    <button
        @click.prevent="nextPage"
        class="action-next"
        type="button"
        title="<?= $escaper->escapeHtml(__('Next Page')) ?>"
        <?= ($page >= $totalPages) ? 'disabled' : '' ?>></button>
</div>
