<?php declare(strict_types=1);

/** @version 0.7.2 */

use Loki\AdminComponents\Form\Field\FieldType\CategorySelection;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Form\Field\Field;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var Field $field */
/** @var CategorySelection $fieldType */

$viewModel = $block->getData('view_model');
$field = $block->getField();
$fieldType = $field->getFieldType();
$categoryTreeNodes = $fieldType->getCategoryTree();
?>
<div
    class="<?= $escaper->escapeHtml($css('admin__field', '@todo')) ?>"
    data-index="container_category_ids"
    x-data="CategorySelection"
    :class="<?= $escaper->escapeHtml($css('classAdminField', '@todo')) ?>"
>
    <div class="<?= $escaper->escapeHtml($css('admin__field-control admin__control-grouped', '@todo')) ?>">
        <div class="<?= $escaper->escapeHtml($css('admin__field', '@todo')) ?>" data-index="category_ids">
            <div class="<?= $escaper->escapeHtml($css('admin__field-label', '@todo')) ?>">
                <label for="category-selection-box">
                    <span :data-config-scope="scopeLabel">
                        <?= $escaper->escapeHtml($field->getLabel()) ?>
                    </span>
                </label>
            </div>
            <div class="<?= $escaper->escapeHtml($css('admin__field-control', '@todo')) ?>">
                <div
                    id="category-selection-box"
                    class="<?= $escaper->escapeHtml($css('admin__action-multiselect-wrap action-select-wrap admin__action-multiselect-tree', '@todo')) ?>"
                    tabindex="0"
                    :class="<?= $escaper->escapeHtml($css('classMultiselectWrap', '@todo')) ?>"
                    @keydown="keydownSwitcher"
                    @click.outside="closeSelector"
                    @keydown.escape.window="closeSelector"
                >
                    <div class="<?= $escaper->escapeHtml($css('action-select admin__action-multiselect', '@todo')) ?>"
                         data-role="advanced-select"
                         :class="<?= $escaper->escapeHtml($css('classMultiselect', '@todo')) ?>"
                         @click="toggleListVisible"
                    >
                        <?= /** @noEscape */ $fieldType->renderCategoriesBreadcrumb() ?>
                    </div>
                    <div class="<?= $escaper->escapeHtml($css('action-menu', '@todo')) ?>"
                         :class="<?= $escaper->escapeHtml($css('classActionMenu', '@todo')) ?>"
                    >
                        <?= /** @noEscape */ $fieldType->renderSearchInput() ?>
                        <?php foreach ($categoryTreeNodes as $rootCategory): ?>
                        <ul class="<?= $escaper->escapeHtml($css('admin__action-multiselect-menu-inner _root', '@todo')) ?>"
                            data-item-data="<?= $escaper->escapeHtmlAttr($fieldType->getCategoryNodeJson($rootCategory)) ?>"
                            x-data="CategorySelectItem"
                            x-show="isTreeView"
                            x-cloak
                            :data-level="itemLevel"
                            :data-expanded="dataExpanded"
                        >
                            <li class="<?= $escaper->escapeHtml($css('admin__action-multiselect-menu-inner-item _root', '@todo')) ?>"
                                data-role="option-group"
                                :class="<?= $escaper->escapeHtml($css('classInnerItem', '@todo')) ?>"
                            >
                                <div class="<?= $escaper->escapeHtml($css('action-menu-item', '@todo')) ?>"
                                     :class="<?= $escaper->escapeHtml($css('classActionMenuItem', '@todo')) ?>"
                                     @mouseenter="handleMouseEnter"
                                     @mouseleave="handleMouseLeave"
                                     @click="toggleSelection"
                                     @keydown.enter.window="toggleSelection"
                                >
                                    <template x-if="showIconToOpenLevels">
                                        <div class="<?= $escaper->escapeHtml($css('admin__action-multiselect-dropdown', '@todo')) ?>"
                                             @click="toggleExpansion"
                                        ></div>
                                    </template>
                                    <input
                                        class="<?= $escaper->escapeHtml($css('admin__control-checkbox', '@todo')) ?>"
                                        type="checkbox"
                                        tabindex="-1"
                                        :checked="isSelected"
                                    />
                                    <label class="<?= $escaper->escapeHtml($css('admin__action-multiselect-label', '@todo')) ?>">
                                        <span><?= $escaper->escapeHtml($rootCategory->label) ?></span>
                                    </label>
                                </div>
                                <?php foreach ($rootCategory->children as $childCategory): ?>
                                    <?= /** @noEscape */ $fieldType->renderChildCategoryNode($childCategory, $field)?>
                                <?php endforeach; ?>
                            </li>
                        </ul>
                        <?php endforeach; ?>

                        <div class="<?= $escaper->escapeHtml($css('admin__action-multiselect-actions-wrap', '@todo')) ?>">
                            <button
                                class="<?= $escaper->escapeHtml($css('action-default', '@todo')) ?>"
                                data-action="close-advanced-select"
                                type="button"
                                @click="closeSelector"
                            >
                                <span><?= $escaper->escapeHtml(__('Done')) ?></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?= /** @noEscape */ $fieldType->renderMainScript($field) ?>
