<?php
declare(strict_types=1);

use Loki\AdminComponents\Component\Grid\GridRepository;
use Loki\AdminComponents\Component\Grid\GridViewModel;
use Loki\AdminComponents\Form\Field\Field;
use Loki\AdminComponents\Form\Field\FieldType\Input;
use Loki\AdminComponents\ViewModel\Form\Field\EntitySelect;
use Loki\Components\Component\Component;
use Loki\Components\Component\ComponentContext;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Block\TemplateRenderer;
use Magento\Customer\Model\ResourceModel\Customer;
use Magento\Customer\Model\ResourceModel\Customer\Collection;
use Magento\Framework\App\ObjectManager;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 0.4.4 */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var Field $field */
/** @var Input $fieldType */
/** @var TemplateRenderer $templateRenderer */
/** @var ViewModelFactory $viewModelFactory */
/** @var EntitySelect $entitySelect */

$entitySelect = $viewModelFactory->create(EntitySelect::class);

$field = $block->getField();
$fieldAttributes = $field->getFieldAttributes();
$fieldType = $field->getFieldType();
$inputType = $fieldType->getInputType();

if (isset($fieldAttributes['type'])) {
    $inputType = $fieldAttributes['type'];
    unset($fieldAttributes['type']);
}

$buttonLabel = $field->getButtonLabel();
if (empty($buttonLabel)) {
    $buttonLabel = 'Select entity';
}

/** @var Component $component */
$namespace = $field->getNamespace();
if ($namespace) {
    $block->setNamespace($namespace);
}



$block->setResourceModel(Customer::class);
$block->setProvider(ObjectManager::getInstance()->get(Collection::class));

$component = ObjectManager::getInstance()->create(Component::class, [
    'name' => $block->getNameInLayout(),
    'viewModelClass' => GridViewModel::class,
    'repositoryClass' => GridRepository::class,
    'context' => ObjectManager::getInstance()->create(ComponentContext::class),
]);

/** @var GridViewModel $gridViewModel */
$gridViewModel = $component->getViewModel();
$columns = $gridViewModel->getColumns();

$currentId = 1;
$currentItem = $gridViewModel->getCurrentItem($currentId);

// @todo: Modal effect with _show does not animate
$valueCode = $field->getScope() . '.' . $field->getCode();
?>
<div
    x-data="LokiAdminFormEntitySelectComponent"
    @keyup.esc="closeWrapper"
    data-value-code="<?= $valueCode ?>"
>
    <div class="input-with-button">
        <input
            class="admin__control-text"
            type="<?= $escaper->escapeHtml($inputType) ?>"
            name="<?= $escaper->escapeHtml($field->getCode()) ?>"
            data-name="<?= $escaper->escapeHtml($field->getCode()) ?>"
            <?php foreach ($fieldAttributes as $attributeName => $attributeValue) :?>
                <?= /* @noEscape */ $attributeName ?>="<?= /* @noEscape */ $attributeValue ?>"
            <?php endforeach; ?>
            :value="<?= $escaper->escapeHtml($valueCode) ?>"
            @change="<?= $escaper->escapeHtml($field->getAlpineSetter()) ?>"
        >

        <button @click="showModalWrapper"><?= __($buttonLabel) ?></button>
    </div>

    <template x-teleport="body">
        <div class="modals-wrapper" x-show="isModalWrapperVisible">
            <aside
                role="dialog"
                x-ref="aside"
                class="modal-slide"
                data-role="modal"
                data-type="popup">
                <div class="modal-inner-wrap" style="padding:20px;">
                    <header class="modal-header">
                        <h1 class="modal-title" data-role="title">
                            Select an entity
                        </h1>
                        <button
                            @click="closeWrapper"
                            class="action-close"
                            type="button">
                            <span>Close</span>
                        </button>



                    </header>

                        <div class="admin__data-grid-header">
                        <div class="admin__data-grid-header-row">
                            <div class="data-grid-search-control-wrap">
                                <input
                                    class="admin__control-text data-grid-search-control"
                                    type="text"
                                    :value="search"
                                    @keyup="setSearch"
                                    placeholder="Search by keyword"
                                    aria-label="Search by keyword"
                                />

                                <button class="action-submit" type="button" data-bind="attr: {'aria-label': $t('Search')}, click: apply.bind($data, false)" aria-label="Search">
                                    <span data-bind="i18n: 'Search'">Search</span>
                                </button>
                            </div>
                        </div>

                            <div class="admin__data-grid-wrap" data-role="grid-wrapper">
                        <table class="data-grid" data-role="grid">
                            <thead>
                            <tr>
                                <th class="data-grid-th">
                                    &nbsp;
                                </th>
                                <?php foreach ($columns as $column) : ?>
                                <th class="data-grid-th">
                                    <span class="data-grid-cell-content">
                                        <?= $column->getLabel() ?>
                                    </span>
                                </th>
                                <?php endforeach; ?>
                            </tr>
                            </thead>
                            <tbody>
                            <template x-if="hasEntities">
                            <template x-for="entity in entities" :key="entity.entity_id">
                            <tr class="data-row">
                                <td class="data-grid-cell">
                                    <button @click="selectEntity(entity)">Select</button>
                                </td>
                                <?php foreach ($columns as $column) : ?>
                                    <td class="data-grid-cell">
                                        <div class="data-grid-cell-content" x-html="entity.<?= $column->getCode() ?>"></div>
                                    </td>
                                <?php endforeach; ?>
                            </tr>
                            </template>
                            </template>
                            <template x-if="hasNoEntities">
                                <tr class="data-row">
                                    <td class="data-grid-cell" colspan="<?= count($columns) + 1 ?>">
                                        No items found
                                    </td>
                                </tr>
                            </template>
                            </tbody>
                        </table>
                    </div>
                    </div>
                </div>
            </aside>
            <div class="modals-overlay"></div>
        </div>
    </template>
</div>

<style>
    .input-with-button {
        display: flex;
    }

    .input-with-button .admin__control-text {
        width: auto !important;
        flex-grow: 1;
        margin-right: 4px;
    }

    .entity-select-iframe {
        width: 100%;
        height: 100%;
    }
</style>

<script>
    window.addEventListener("message", (event) => {
        if (event.data.type === "lokiAdminOnSelectEntity") {
            console.log("Signal received:", event.data.data);
        }
    });
</script>

