<?php
declare(strict_types=1);

use Loki\AdminComponents\Form\Field\Field;
use Loki\AdminComponents\Form\Field\FieldType\Input;
use Loki\AdminComponents\ViewModel\Form\Field\EntitySelect;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Block\TemplateRenderer;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 0.5.1 */
/** @var Escaper $escaper */
/** @var Template $block */
/** @var Field $field */
/** @var Input $fieldType */
/** @var TemplateRenderer $templateRenderer */
/** @var ViewModelFactory $viewModelFactory */
/** @var EntitySelect $entitySelect */

$entitySelect = $viewModelFactory->create(EntitySelect::class, [
    'block' => $block
]);

$field = $entitySelect->getField();
$fieldAttributes = $field->getFieldAttributes();
$fieldType = $field->getFieldType();
$inputType = $fieldType->getInputType();
$buttonLabel = $entitySelect->getButtonLabel();
$modalTitle = $entitySelect->getModalTitle();

if (isset($fieldAttributes['type'])) {
    $inputType = $fieldAttributes['type'];
    unset($fieldAttributes['type']);
}

$columns = $entitySelect->getColumns();
$currentItem = $entitySelect->getCurrentItem();
$valueCode = $entitySelect->getValueCode();

// @todo: Modal effect with _show does not animate
?>
<div
    x-data="LokiAdminFormEntitySelectComponent"
    @keyup.esc="closeWrapper"
    data-value-code="<?= $escaper->escapeHtml($valueCode) ?>"
>
    <script x-ref="initialData" type="text/x-loki-init"><?= /* @noEscape */ $entitySelect->getJsonData() ?></script>

    <div class="input-with-button">
        <input
            class="admin__control-text"
            type="<?= $escaper->escapeHtml($inputType) ?>"
            name="<?= $escaper->escapeHtml($field->getCode()) ?>"
            data-name="<?= $escaper->escapeHtml($field->getCode()) ?>"
            <?php foreach ($fieldAttributes as $attributeName => $attributeValue) :?>
                <?= /* @noEscape */ $attributeName ?>="<?= /* @noEscape */ $attributeValue ?>"
            <?php endforeach; ?>
            :value="<?= $escaper->escapeHtml($valueCode) ?>"
            @change="<?= $escaper->escapeHtml($field->getAlpineSetter()) ?>"
        >

        <button @click="showModalWrapper"><?= $escaper->escapeHtml(__($buttonLabel)) ?></button>
    </div>

    <template x-teleport="body">
        <div class="modals-wrapper" x-show="isModalWrapperVisible">
            <aside
                role="dialog"
                x-ref="aside"
                class="modal-slide"
                data-role="modal"
                data-type="popup">
                <div class="modal-inner-wrap" style="padding:20px;">
                    <header class="modal-header">
                        <h1 class="modal-title" data-role="title">
                            <?= $escaper->escapeHtml($modalTitle) ?>
                        </h1>
                        <button
                            @click="closeWrapper"
                            class="action-close"
                            type="button">
                            <span>Close</span>
                        </button>



                    </header>

                        <div class="admin__data-grid-header">
                        <div class="admin__data-grid-header-row">
                            <div class="data-grid-search-control-wrap">
                                <input
                                    class="admin__control-text data-grid-search-control"
                                    type="text"
                                    :value="search"
                                    @keyup="setSearch"
                                    placeholder="Search by keyword"
                                    aria-label="Search by keyword"
                                />

                                <button class="action-submit" type="button" aria-label="Search">
                                    <span>Search</span>
                                </button>
                            </div>
                        </div>

                            <div class="admin__data-grid-wrap" data-role="grid-wrapper">
                        <table class="data-grid" data-role="grid">
                            <thead>
                            <tr>
                                <th class="data-grid-th">
                                    &nbsp;
                                </th>
                                <?php foreach ($columns as $column) : ?>
                                <th class="data-grid-th">
                                    <span class="data-grid-cell-content">
                                        <?= $escaper->escapeHtml($column->getLabel()) ?>
                                    </span>
                                </th>
                                <?php endforeach; ?>
                            </tr>
                            </thead>
                            <tbody>
                            <template x-if="hasEntities">
                            <template x-for="entity in entities" :key="entity.entity_id">
                            <tr class="data-row">
                                <td class="data-grid-cell">
                                    <button @click="selectEntity(entity)">Select</button>
                                </td>
                                <?php foreach ($columns as $column) : ?>
                                    <td class="data-grid-cell">
                                        <div class="data-grid-cell-content" x-html="entity.<?= $escaper->escapeHtml($column->getCode()) ?>"></div>
                                    </td>
                                <?php endforeach; ?>
                            </tr>
                            </template>
                            </template>
                            <template x-if="hasNoEntities">
                                <tr class="data-row">
                                    <td class="data-grid-cell" colspan="<?= count($columns) + 1 ?>">
                                        No items found
                                    </td>
                                </tr>
                            </template>
                            </tbody>
                        </table>
                    </div>
                    </div>
                </div>
            </aside>
            <div class="modals-overlay"></div>
        </div>
    </template>
</div>

<style>
    .input-with-button {
        display: flex;
    }

    .input-with-button .admin__control-text {
        width: auto !important;
        flex-grow: 1;
        margin-right: 4px;
    }

    .entity-select-iframe {
        width: 100%;
        height: 100%;
    }
</style>

<script>
    window.addEventListener("message", (event) => {
        if (event.data.type === "lokiAdminOnSelectEntity") {
            console.log("Signal received:", event.data.data);
        }
    });
</script>

