<?php
declare(strict_types=1);

/** @version 0.2.5 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Form\Field\Field;
use Loki\AdminComponents\Form\Field\FieldType\Text;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var Field $field */
/** @var Text $fieldType */
/** @var TemplateRenderer $templateRenderer */

$field = $block->getField();
$fieldType = $field->getFieldType();
?>
<div class="">
    <div class="admin__form-field">
        <label class="admin__form-field-label">
            <span>from</span>
        </label>

        <div class="admin__form-field-control">
            <input
                class="admin__control-text"
                type="text"
                data-name="<?= $escaper->escapeHtml($field->getCode()) ?>"
                maxlength="<?= $escaper->escapeHtml(
                    $fieldType->getMaximumLength()
                ) ?>"
                :value="<?= $escaper->escapeHtml($field->getScope()) ?>.<?= $escaper->escapeHtml($field->getCode()) ?>"
                @change="setValue"
                placeholder="<?= $escaper->escapeHtml(
                    $field->getBlock()->getPlaceholder()
                ) ?>"
            >
        </div>
    </div>

    <div class="admin__form-field">
        <label class="admin__form-field-label">
            <span>to</span>
        </label>

        <div class="admin__form-field-control">
            <input
                class="admin__control-text"
                type="text"
                data-name="<?= $escaper->escapeHtml($field->getCode()) ?>"
                maxlength="<?= $escaper->escapeHtml(
                    $fieldType->getMaximumLength()
                ) ?>"
                :value="<?= $escaper->escapeHtml($field->getScope()) ?>.<?= $escaper->escapeHtml($field->getCode()) ?>"
                @change="setValue"
                placeholder="<?= $escaper->escapeHtml(
                    $field->getBlock()->getPlaceholder()
                ) ?>"
            >
        </div>
    </div>
</div>
