<?php
declare(strict_types=1);

/** @version 0.6.0 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Form\Field\Field;
use Loki\AdminComponents\Form\Field\FieldType\Input;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var Field $field */
/** @var Input $fieldType */
/** @var TemplateRenderer $templateRenderer */

$field = $block->getField();
$fieldType = $field->getFieldType();
$inputType = $field->getInputType();
if (empty($inputType)) {
    $inputType = 'text';
}
?>
<div class="">
    <div class="admin__form-field">
        <label
            for="<?= $escaper->escapeHtml($field->getScope()) ?>.<?= $escaper->escapeHtml($field->getCode()) ?>"
            class="admin__form-field-label">
            <span>from</span>
        </label>

        <div class="admin__form-field-control">
            <input
                id="<?= $escaper->escapeHtml($field->getScope()) ?>.<?= $escaper->escapeHtml($field->getCode()) ?>"
                class="admin__control-text"
                type="<?= $escaper->escapeHtml($inputType) ?>"
                data-name="<?= $escaper->escapeHtml($field->getCode()) ?>.from"
                maxlength="<?= $escaper->escapeHtml(
                    $fieldType->getMaximumLength()
                ) ?>"
                :value="<?= $escaper->escapeHtml($field->getScope()) ?>.<?= $escaper->escapeHtml($field->getCode()) ?>.from"
                @change="<?= $escaper->escapeHtml($field->getAlpineSetter()) ?>"
                placeholder="<?= $escaper->escapeHtml(
                    $field->getBlock()->getPlaceholder()
                ) ?>"
            >
        </div>
    </div>

    <div class="admin__form-field">
        <label class="admin__form-field-label">
            <span>to</span>
        </label>

        <div class="admin__form-field-control">
            <input
                class="admin__control-text"
                type="<?= $escaper->escapeHtml($inputType) ?>"
                data-name="<?= $escaper->escapeHtml($field->getCode()) ?>.to"
                maxlength="<?= $escaper->escapeHtml(
                    $fieldType->getMaximumLength()
                ) ?>"
                :value="<?= $escaper->escapeHtml($field->getScope()) ?>.<?= $escaper->escapeHtml($field->getCode()) ?>.to"
                @change="<?= $escaper->escapeHtml($field->getAlpineSetter()) ?>"
                placeholder="<?= $escaper->escapeHtml(
                    $field->getBlock()->getPlaceholder()
                ) ?>"
            >
        </div>
    </div>
</div>
