<?php
declare(strict_types=1);

use Magento\Framework\Data\OptionSourceInterface;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Form\Field\Field;
use Loki\AdminComponents\Form\Field\FieldType\Select;
use Yireo\LokiComponents\Util\Block\TemplateRenderer;

/** @var Template $block */
/** @var Field $field */
/** @var Select $fieldType */
/** @var OptionSourceInterface $options */
/** @var TemplateRenderer $templateRenderer */

$field = $block->getField();
$parentBlock = $field->getBlock();
$options = $parentBlock->getOptions();
$emptyOption = $parentBlock->getEmptyOption();
$fieldType = $field->getFieldType();
?>
<select
    aria-label="<?= $field->getLabel() ?>"
    class="admin__control-select"
    name="<?= $field->getCode() ?>"
    data-name="<?= $field->getCode() ?>"
    <?php if ($parentBlock->getMultiple()) : ?>multiple<?php endif; ?>
    <?php if ($parentBlock->getSize()) : ?>size="<?= $parentBlock->getSize() ?>"<?php endif; ?>
    :value="<?= $field->getScope() ?>.<?= $field->getCode() ?>"
    @change="setValue"
>
    <?php if (!empty($emptyOption)): ?>
        <?= $templateRenderer->html(
            $block,
            'Loki_AdminComponents::form/field_type/select/option.phtml',
            [
                'option' => [
                    'value' => '',
                    'label' => $emptyOption,
                    'level' => 0,
                ],
            ]
        ) ?>
    <?php endif; ?>
    <?php foreach ($options->toOptionArray() as $option) : ?>
        <?= $option['level'] = 0; ?>
        <?= $templateRenderer->html(
            $block,
            'Loki_AdminComponents::form/field_type/select/option.phtml',
            ['option' => $option]
        ) ?>
    <?php endforeach; ?>
</select>
