<?php
declare(strict_types=1);

use Magento\Framework\Data\OptionSourceInterface;
use Magento\Framework\View\Element\Template;
use Yireo\LokiAdminComponents\Form\Field\Field;
use Yireo\LokiAdminComponents\Form\Field\FieldType\Select;
use Yireo\LokiComponents\Util\Block\TemplateRenderer;

/** @var Template $block */
/** @var Field $field */
/** @var Select $fieldType */
/** @var OptionSourceInterface $options */
/** @var TemplateRenderer $templateRenderer */

$field = $block->getField();
$parentBlock = $field->getBlock();
$options = $parentBlock->getOptions();
$fieldType = $field->getFieldType();
?>
<select
    aria-label="<?= $field->getLabel() ?>"
    class="admin__control-select"
    data-name="<?= $field->getCode() ?>"
    <?php if ($parentBlock->getMultiple()) : ?>multiple<?php endif; ?>
    <?php if ($parentBlock->getSize()) : ?>size="<?= $parentBlock->getSize() ?>"<?php endif; ?>
    :value="<?= $field->getScope() ?>.<?= $field->getCode() ?>"
    @change="setValue"
>
    <?php foreach ($options->toOptionArray() as $option) : ?>
        <?php if (is_array($option['value'])): ?>
        <?php else: ?>
            <option value="<?= $option['value'] ?>"><?= $option['label'] ?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
