<?php
declare(strict_types=1);

/** @version 0.4.0 */

use Magento\Framework\Escaper;
use Magento\Framework\Data\OptionSourceInterface;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Form\Field\Field;
use Loki\AdminComponents\Form\Field\FieldType\Select;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var Field $field */
/** @var Select $fieldType */
/** @var OptionSourceInterface $options */
/** @var TemplateRenderer $templateRenderer */

$field = $block->getField();
$options = $field->getOptions();
$fieldType = $field->getFieldType();
?>
<div class="admin__actions-switch">
    <input
        type="checkbox"
        name="<?= $escaper->escapeHtml($field->getCode()) ?>"
        class="admin__actions-switch-checkbox"
        :checked="<?= $escaper->escapeHtml($field->getScope()) ?>.<?= $escaper->escapeHtml($field->getCode()) ?>"
        @change="<?= $escaper->escapeHtml($field->getAlpineSetter()) ?>"
    >
    <label
        class="admin__actions-switch-label"
        @click.prevent="toggleValueByClick"
        data-name="<?= $escaper->escapeHtml($field->getCode()) ?>"
        data-value="<?= $escaper->escapeHtml($field->getScope()) ?>.<?= $escaper->escapeHtml($field->getCode()) ?>"
    >
        <span class="admin__actions-switch-text" x-show="item.<?= $escaper->escapeHtml($field->getCode()) ?>">Yes</span>
        <span class="admin__actions-switch-text" x-show="!item.<?= $escaper->escapeHtml($field->getCode()) ?>">No</span>
    </label>
</div>
