<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Yireo\LokiAdminComponents\Form\Field\Field;
use Yireo\LokiAdminComponents\Form\Field\FieldType\Text;
use Yireo\LokiComponents\Util\Block\TemplateRenderer;

/** @var Template $block */
/** @var Field $field */
/** @var Text $fieldType */
/** @var TemplateRenderer $templateRenderer */

$field = $block->getField();
$fieldType = $field->getFieldType();
?>
<input
    class="admin__control-text"
    type="<?= $fieldType->getInputType() ?>"
    data-name="<?= $field->getCode() ?>"
    placeholder="<?= $field->getBlock()->getPlaceholder() ?>"
    maxlength="<?= $fieldType->getMaximumLength() ?>"
    :value="<?= $field->getScope() ?>.<?= $field->getCode() ?>"
    @change="setValue"
>
