<?php
declare(strict_types=1);

/** @version 0.2.5 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Form\Field\Field;
use Loki\AdminComponents\Form\Field\FieldType\Text;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var Field $field */
/** @var Text $fieldType */
/** @var TemplateRenderer $templateRenderer */

$field = $block->getField();
$fieldAttributes = $field->getFieldAttributes();
$fieldType = $field->getFieldType();
$inputType = $fieldType->getInputType();
if (isset($fieldAttributes['type'])) {
    $inputType = $fieldAttributes['type'];
    unset($fieldAttributes['type']);
}
?>
<input
    class="admin__control-text"
    type="<?= $escaper->escapeHtml($inputType) ?>"
    name="<?= $escaper->escapeHtml($field->getCode()) ?>"
    data-name="<?= $escaper->escapeHtml($field->getCode()) ?>"
    <?php foreach ($fieldAttributes as $attributeName => $attributeValue) : ?>
        <?= /* @noEscape */ $attributeName ?>="<?= /* @noEscape */ $attributeValue ?>"
    <?php endforeach; ?>
    :value="<?= $escaper->escapeHtml($field->getScope()) ?>.<?= $escaper->escapeHtml($field->getCode()) ?>"
    @change="setValue"
>
