<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Form\Field\Field;
use Loki\AdminComponents\Form\Field\FieldType\Text;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Template $block */
/** @var Field $field */
/** @var Text $fieldType */
/** @var TemplateRenderer $templateRenderer */

$field = $block->getField();
$htmlAttributes = $field->getHtmlAttributes();
$fieldType = $field->getFieldType();
$inputType = $fieldType->getInputType();
if (isset($htmlAttributes['type'])) {
    $inputType = $htmlAttributes['type'];
    unset($htmlAttributes['type']);
}
?>
<input
    class="admin__control-text"
    type="<?= $escaper->escapeHtml($inputType) ?>"
    name="<?= $escaper->escapeHtml($field->getCode()) ?>"
    data-name="<?= $escaper->escapeHtml($field->getCode()) ?>"
    <?php foreach ($htmlAttributes as $htmlAttributeName => $htmlAttributeValue) : ?>
        <?= /* @noEscape */
$htmlAttributeName ?>="<?= /* @noEscape */
$htmlAttributeValue ?>"
    <?php endforeach; ?>
    :value="<?= $escaper->escapeHtml($field->getScope()) ?>.<?= $escaper->escapeHtml($field->getCode()) ?>"
    @change="setValue"
>
