<?php
declare(strict_types=1);

/** @version 0.4.2 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Form\Field\Field;
use Loki\AdminComponents\Form\Field\FieldType\Textarea;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var Field $field */
/** @var Textarea $fieldType */
/** @var TemplateRenderer $templateRenderer */

$field = $block->getField();
$fieldAttributes = $field->getFieldAttributes();
$fieldType = $field->getFieldType();
?>
<textarea
    class="admin__control-text"
    name="<?= $escaper->escapeHtml($field->getCode()) ?>"
    data-name="<?= $escaper->escapeHtml($field->getCode()) ?>"
    <?php foreach ($fieldAttributes as $attributeName => $attributeValue) : ?>
        <?= /* @noEscape */ $attributeName ?>="<?= /* @noEscape */ $attributeValue ?>"
    <?php endforeach; ?>
    :value="<?= $escaper->escapeHtml($field->getScope()) ?>.<?= $escaper->escapeHtml($field->getCode()) ?>"
    @change="<?= $escaper->escapeHtml($field->getAlpineSetter()) ?>"
></textarea>
