<?php
declare(strict_types=1);

/** @version 0.4.4 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\Form\Field\Field;
use Loki\AdminComponents\Form\Field\FieldType\Input;
use Loki\Components\Util\Block\TemplateRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var Field $field */
/** @var Input $fieldType */
/** @var TemplateRenderer $templateRenderer */

$field = $block->getField();
$fieldType = $field->getFieldType();

?>
<div style="padding-top:8px;" x-html="<?= $escaper->escapeHtml($field->getScope()) ?>.<?= $escaper->escapeHtml($field->getCode()) ?>"></div>
