<?php
declare(strict_types=1);

/** @version 0.3.2 */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Catalog\Api\Data\ProductInterface;
use Loki\AdminComponents\ViewModel\AttributeSet;
use Loki\Components\Factory\ViewModelFactory;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var Magento\Framework\View\Element\Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ProductInterface $item */
/** @var AttributeSet $attributeSet */

$attributeSet = $viewModelFactory->create(AttributeSet::class);
?>
<span><?= $escaper->escapeHtml($attributeSet->getLabel((int)$block->getValue())) ?></span>
