<?php
declare(strict_types=1);

use Magento\Catalog\Api\Data\ProductInterface;
use Loki\AdminComponents\ViewModel\AttributeSet;
use Loki\Components\Factory\ViewModelFactory;

/** @var Magento\Framework\View\Element\Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ProductInterface $item */
/** @var AttributeSet $attributeSet */

$attributeSet = $viewModelFactory->create(AttributeSet::class);
?>
<span><?= $attributeSet->getLabel((int)$block->getValue()) ?></span>
