<?php
declare(strict_types=1);

/** @version 0.6.1 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\ViewModel\Customer;
use Loki\Components\Factory\ViewModelFactory;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var Customer $customerViewModel */
/** @var Escaper $escaper */

$customerViewModel = $viewModelFactory->create(Customer::class);
$customerId = (int)$block->getValue();
$customer = $customerViewModel->getById($customerId);
?>
<span><?= $escaper->escapeHtml($customerId) ?> (<?= $escaper->escapeHtml($customer?->getEmail()) ?>)</span>
