<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 0.4.0 */
/** @var Escaper $escaper */
/** @var Template $block */
$value = $block->getValue();
$emptyValue = $block->getEmptyValue();

if (empty($value) && !empty($emptyValue)) {
    $value = $emptyValue;
}

if (is_array($value)) {
    $value = 'array';
}

if (is_object($value)) {
    $value = 'object';
}
?>
<?php echo $escaper->escapeHtml($value) ?>
