<?php
declare(strict_types=1);

/** @version 0.3.2 */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Framework\DataObject;
use Loki\Components\Factory\ViewModelFactory;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var Magento\Framework\View\Element\Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var DataObject $item */

$item = $block->getItem();
?>
<div x-data="LokiAdminInlineEditComponent">
    <span @dblclick="toggleInlineEdit" x-show="hideInlineEdit">
        <?= $escaper->escapeHtml($block->getValue()) ?>
    </span>

    <span x-show="showInlineEdit">
        <input
            x-ref="inlineEditField"
            type="text"
            class="admin__control-text"
            value="<?= $escaper->escapeHtml($block->getValue()) ?>"
        />

        <button
            class="action-close"
            @click.prevent="toggleInlineEdit"
        ></button>

        <button
            class="action-save"
            @click.prevent="saveInlineEdit"
            data-identifier="<?= $escaper->escapeHtml($item->getId()) ?>"
            data-property="<?= $escaper->escapeHtml($block->getColumnName()) ?>"
        >save</button>
    </span>
</div>
