<?php
declare(strict_types=1);

use Magento\Catalog\Api\Data\ProductInterface;
use Yireo\LokiAdminComponents\ViewModel\PriceFormatter;
use Yireo\LokiComponents\Factory\ViewModelFactory;

/** @var Magento\Framework\View\Element\Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ProductInterface $item */
/** @var PriceFormatter $priceFormatter */

?>
<div x-data="LokiToggle">
    <span @dblclick="toggle" x-show="shown">
        <?= $block->getValue() ?>
    </span>
    <span x-show="hidden">
        <input type="text" class="admin__control-text" value="<?= $block->getValue() ?>"/>
    </span>
</div>
