<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Framework\DataObject;
use Loki\Components\Factory\ViewModelFactory;

/** @version 0.6.4 */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var Magento\Framework\View\Element\Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var DataObject $item */

$item = $block->getItem();
$fieldId = $block->getColumnName().'-'.$item->getId();
?>
<div x-data="LokiAdminInlineEditComponent" @dblclick="toggleInlineEdit">
    <label
        for="<?= $escaper->escapeHtmlAttr($fieldId) ?>"
        @dblclick="toggleInlineEdit"
        x-show="hideInlineEdit"
    >
        <?= $escaper->escapeHtml($block->getValue()) ?>
    </label>

    <span x-show="showInlineEdit">
        <input
            id="<?= $escaper->escapeHtmlAttr($fieldId) ?>"
            x-ref="inlineEditField"
            type="text"
            class="admin__control-text"
            value="<?= $escaper->escapeHtml($block->getValue()) ?>"
        />

        <button
            class="action-close2"
            @click.prevent="toggleInlineEdit"
        >
            <?= $escaper->escapeHtml(__('Close')) ?>
        </button>

        <button
            class="action-save"
            @click.prevent="saveInlineEdit"
            data-identifier="<?= $escaper->escapeHtml($item->getId()) ?>"
            data-property="<?= $escaper->escapeHtml($block->getColumnName()) ?>"
        >
            <?= $escaper->escapeHtml(__('Save')) ?>
        </button>
    </span>
</div>
