<?php
declare(strict_types=1);

use Magento\Catalog\Api\Data\ProductInterface;
use Loki\AdminComponents\ViewModel\ProductImage;
use Loki\AdminComponents\ViewModel\PriceFormatter;
use Yireo\LokiComponents\Factory\ViewModelFactory;

/** @var Magento\Framework\View\Element\Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ProductInterface $item */
/** @var PriceFormatter $priceFormatter */

$priceFormatter = $viewModelFactory->create(PriceFormatter::class);
?>
<span><?= $priceFormatter->format($block->getValue()) ?></span>
