<?php
declare(strict_types=1);

use Magento\Catalog\Api\Data\ProductInterface;
use Yireo\LokiAdminComponents\ViewModel\ProductType;
use Yireo\LokiAdminComponents\ViewModel\Status;
use Yireo\LokiComponents\Factory\ViewModelFactory;

/** @var Magento\Framework\View\Element\Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ProductInterface $item */
/** @var ProductType $productType */

$productType = $viewModelFactory->create(ProductType::class);
?>
<span><?= $productType->getLabel($block->getValue()) ?></span>
