<?php
declare(strict_types=1);

/** @version 0.5.0 */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Catalog\Api\Data\ProductInterface;
use Loki\AdminComponents\ViewModel\ProductImage;
use Loki\Components\Factory\ViewModelFactory;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var Magento\Framework\View\Element\Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ProductImage $productImage */
/** @var ProductInterface $item */

$productImage = $viewModelFactory->create(ProductImage::class);
$item = $block->getItem();
?>
<span class="thumbnail-container" x-data="LokiModal">
    <span class="thumbnail-wrapper">
        <img @click.prevent="toggleModal" class="admin__control-thumbnail" src="<?= /* @noEscape */ $productImage->getThumbnailUrl($item) ?>"
             loading="lazy" alt="<?= $escaper->escapeHtml($item->getName()) ?>"/>
    </span>

    <dialog x-ref="modal" @click.prevent="toggleModal">
    <span class="">
        <h2><?= $escaper->escapeHtml($item->getName()) ?></h2>
        <img src="<?= /* @noEscape */ $productImage->getImageUrl($item) ?>" loading="lazy" alt="<?= $escaper->escapeHtml($item->getName()) ?>"/>
    </span>
    </dialog>
</span>
