<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Catalog\Api\Data\ProductInterface;
use Loki\AdminComponents\ViewModel\ProductType;
use Loki\AdminComponents\ViewModel\Status;
use Loki\Components\Factory\ViewModelFactory;

/** @version 0.7.2 */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var Magento\Framework\View\Element\Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ProductInterface $item */
/** @var ProductType $productType */

$productType = $viewModelFactory->create(ProductType::class);
?>
<span><?= $escaper->escapeHtml($productType->getLabel($block->getValue())) ?></span>
