<?php
declare(strict_types=1);

/** @version 0.2.6 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\ViewModel\Product;
use Loki\Components\Factory\ViewModelFactory;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var Product $productViewModel */
$productId = (int)$block->getValue();
if (empty($productId)) {
    return;
}

$productViewModel = $viewModelFactory->create(Product::class);
$product = $productViewModel->getById($productId);
?>
<span><?= $escaper->escapeHtml($product->getId()) ?> (<?= $escaper->escapeHtml($product->getName()) ?>)</span>
