<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Catalog\Api\Data\ProductInterface;
use Loki\AdminComponents\ViewModel\ProductImage;
use Loki\Components\Factory\ViewModelFactory;

/** @version 0.7.2 */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var Magento\Framework\View\Element\Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ProductImage $productImage */
/** @var ProductInterface $item */

$productImage = $viewModelFactory->create(ProductImage::class);
$item = $block->getItem();
?>
<span class="<?= $escaper->escapeHtml($css('thumbnail-container', '@todo')) ?>" x-data="LokiModal">
    <span class="<?= $escaper->escapeHtml($css('thumbnail-wrapper', '@todo')) ?>">
        <img @click.prevent="toggleModal" class="<?= $escaper->escapeHtml($css('admin__control-thumbnail', '@todo')) ?>" src="<?= /* @noEscape */ $productImage->getThumbnailUrl($item) ?>"
             loading="lazy" alt="<?= $escaper->escapeHtml($item->getName()) ?>"/>
    </span>

    <dialog x-ref="modal" @click.prevent="toggleModal">
    <span class="">
        <h2><?= $escaper->escapeHtml($item->getName()) ?></h2>
        <img src="<?= /* @noEscape */ $productImage->getImageUrl($item) ?>" loading="lazy" alt="<?= $escaper->escapeHtml($item->getName()) ?>"/>
    </span>
    </dialog>
</span>
