<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Loki\AdminComponents\ViewModel\Product;
use Loki\Components\Factory\ViewModelFactory;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var Product $productViewModel */

$productViewModel = $viewModelFactory->create(Product::class);
$product = $productViewModel->getById((int)$block->getValue());
?>
<span><?= $escaper->escapeHtml($product->getId()) ?> (<?= $escaper->escapeHtml($product->getName()) ?>)</span>
