<?php
declare(strict_types=1);

/** @version 0.2.3 */

use Magento\Catalog\Api\Data\ProductInterface;
use Loki\AdminComponents\ViewModel\Status;
use Loki\Components\Factory\ViewModelFactory;

/** @var Magento\Framework\View\Element\Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ProductInterface $item */
/** @var Status $status */

$status = $viewModelFactory->create(Status::class);
?>
<span><?= $escaper->escapeHtml($status->getLabel($block->getValue())) ?></span>
