<?php
declare(strict_types=1);

use Loki\AdminComponents\ViewModel\StoreView;
use Loki\Components\Factory\ViewModelFactory;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @version 0.4.1 */
/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelFactory $viewModelFactory */
/** @var StoreView $storeView */
/** @var array $value */

$value = $block->getValue();

if (count($value) === 1 && (int)$value[0] === 0) {
    echo $escaper->escapeHtml(__('All Store Views'));
    return;
}

$storeView = $viewModelFactory->create(StoreView::class);
$storeHierarchy = $storeView->getStoreHierarchy($value);
?>
<ul>
    <?php foreach ($storeHierarchy as $website) : ?>
        <?php if(!$website['selected']) continue; ?>
        <li>
            <?= $escaper->escapeHtml($website['name']) ?> (<?= $escaper->escapeHtml($website['code']) ?>)
            <ul>
                <?php foreach ($website['groups'] as $group) : ?>
                    <?php if(!$group['selected']) continue; ?>
                    <li>
                        <?= $escaper->escapeHtml($group['name']) ?> (<code><?= $escaper->escapeHtml($group['code']) ?></code>)
                        <ul>
                            <?php foreach ($group['stores'] as $store) : ?>
                                <?php if(!$store['selected']) continue; ?>
                                <li>
                                    <?= $escaper->escapeHtml($store['name']) ?> (<code><?= $escaper->escapeHtml($store['code']) ?></code>)
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                <?php endforeach; ?>
            </ul>
        </li>
    <?php endforeach; ?>
</ul>
