<?php
declare(strict_types=1);

/** @version 0.2.6 */

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Catalog\Api\Data\ProductInterface;
use Loki\AdminComponents\ViewModel\ProductImage;
use Loki\AdminComponents\ViewModel\PriceFormatter;
use Loki\AdminComponents\ViewModel\Visibility;
use Loki\Components\Factory\ViewModelFactory;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var Magento\Framework\View\Element\Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var ProductInterface $item */
/** @var Visibility $visibility */

$visibility = $viewModelFactory->create(Visibility::class);
?>
<span><?= $escaper->escapeHtml($visibility->getLabel($block->getValue())) ?></span>
