<?php
declare(strict_types=1);

/** @version 0.3.0 */

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiAdminGridComponent', () => ({
            ...LokiAdminGridComponentType,
            repositionColumns(columnName, position) {
                // @todo: This is really hacky, because the x-sort callback is bound to Window and not the component
                const itemParts = columnName.split('.');
                const componentName = itemParts[0];
                const propertyName = itemParts[1];
                const component = Alpine.store('LokiComponents').get(componentName);
                component.post({reposition: {property: propertyName, position: position}});
            }
        }));
    });

    document.addEventListener('alpine:init', () => {
        Alpine.data('LokiAdminInlineEditComponent', () => ({
            ...LokiAdminInlineEditComponentPartial
        }));
    });
</script>
